### ISSUE TITLE
Bug: Timestamp missing with post

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#100]
### What happened?

Currently with posts, a user can't see at what time it is posted. The backend is storing the time stamp but it is not displaying on the UI. The timestamp is saving in ISO format.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

**Comment by utkarsh4321** [comment]
@Sanchitbajaj02 Can you assign this issue to me. I want to work on this issue.

**Comment by Sanchitbajaj02** [comment]
Sure you can work on that. Assigned

**Comment by utkarsh4321** [comment]
hi @Sanchitbajaj02 i want to ask few things. Like i need to show created At timestamp?.
1.  Where i need to show it? 
2. What should be the format of date?

This coming in post data
<img width="232" alt="image" src="https://github.com/Sanchitbajaj02/palettegram/assets/30936607/3a13e77d-c65d-48a4-8e14-613c9907d316">
This is post where i need to show that time stamp
<img width="417" alt="image" src="https://github.com/Sanchitbajaj02/palettegram/assets/30936607/7ad62e62-8d50-4229-b1f3-5f6be5c46b92">

Please tell thankyou

**Comment by Sanchitbajaj02** [comment]
> Where i need to show it?
You can show it under the ID with small font and less highlighted color. Make sure to handle both light and dark mode.

> What should be the format of date?
I think UTC format with only dates will be good. For example: 01 Jan, 2024. if possible you can show the date like '2h ago', '1d ago', etc.

Hope this helps you 😊

**Comment by utkarsh4321** [comment]
@Sanchitbajaj02 It looks like this
At dark mode
<img width="429" alt="image" src="https://github.com/Sanchitbajaj02/palettegram/assets/30936607/fc2094f5-723c-4aa6-b1fc-5fc77ff31a00">
At light mode
<img width="409" alt="image" src="https://github.com/Sanchitbajaj02/palettegram/assets/30936607/a9e3307b-0cf3-47db-bb97-5e51a59ab6f0">
Pleas give your feedback if that ok then I will create PR for it.
Thankyou

**Comment by Sanchitbajaj02** [comment]
Yeah it is looking great. Please proceed 😊

While creating a PR please mention what you did in the description according to the SWOC guidelines

**Comment by utkarsh4321** [comment]
@Sanchitbajaj02 created PR for this issue please review it. If anything is needed from my end please let me know. I will try to resolve it asap.

Thankyou

**Comment by Sanchitbajaj02** [comment]
Hi @utkarsh4321 added reviews in your PR. Please resolve

**Comment by utkarsh4321** [comment]
Hi @Sanchitbajaj02 please check Pr. I have made changes according to your requirements. I hope it's correct. Let me know any other changes are required.

**Comment by Sanchitbajaj02** [comment]
@utkarsh4321 I have requested more changes related to code. Please resolve that as well so that I can merge the code 😄
