### ISSUE TITLE
Feat: Markdown support for post title

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#101]
### What feature?

Currently, the textarea is implemented to create a postTitle but as we all know it is inefficient in comparison to markdown editor. 
So, it will be great to implement a markdown editor kind of like the one used in GitHub or Stackoverflow, where it is easy for developers to enter code snippet.

### Example: 

```js
const x = '2';
console.log(2 + x);
``` 

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

**Comment by UtkarshUmre** [comment]
i want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Sure, @UtkarshUmre assigned this issue to you

**Comment by Sanchitbajaj02** [comment]
Since didn't get any response from you in a week, I am unassigning @UtkarshUmre

**Comment by UtkarshUmre** [comment]
hey @Sanchitbajaj02 i apologize for the delay. my last week was very busy with work & travel, so i haven't had a chance to look into this issue yet. However, I'll prioritize it & provide with an update within this week

**Comment by Sanchitbajaj02** [comment]
> i apologize for the delay. my last week was very busy with work & travel

You should have informed me. I will assign you this again but if you didn't respond this time, I will definitely resassign to someone

**Comment by IrfanshaikH-7** [comment]
- 🤔 Just a thought - can we use other open-source editors - instead of a text area - 

That'll probably give us even more power then just the markdown : example being
Quotes, bold,italic, and manymore options to format our post title .🤔 And we can render it as a html...

😅Just like a shorter blog impersonating as a post

**Comment by Sanchitbajaj02** [comment]
> * 🤔 Just a thought - can we use other open-source editors - instead of a text area -
> 
> That'll probably give us even more power then just the markdown : example being Quotes, bold,italic, and manymore options to format our post title .🤔 And we can render it as a html...
> 
> 😅Just like a shorter blog impersonating as a post

That's the whole idea on which @UtkarshUmre is working on. Instead of text area, a new markdown editor will be implemented

**Comment by thevirengarg** [comment]
@UtkarshUmre I am un-assigning you this issue.
@IrfanshaikH-7 Do you want to work on this?

**Comment by IrfanshaikH-7** [comment]
> @UtkarshUmre I am un-assigning you this issue. @IrfanshaikH-7 Do you want to work on this?

Obviously - I would love to work on this -

**Comment by thevirengarg** [comment]
@IrfanshaikH-7 But you already have other issue assigned to you. Complete that first, then i will assign you this.

**Comment by IrfanshaikH-7** [comment]
Okay - i'll DM you tonnight - I'm actually done with that issue

**Comment by IrfanshaikH-7** [comment]
@Sanchitbajaj02  can I look into it!

**Comment by thevirengarg** [comment]
@IrfanshaikH-7 Assigned this issue to you.

**Comment by IrfanshaikH-7** [comment]
> @IrfanshaikH-7 Assigned this issue to you.

do you have any editor pakage in mind or m free to use anything.

**Comment by Sanchitbajaj02** [comment]
@IrfanshaikH-7 you can checkout `quill` or it would be better if you inspect what markdown editor does `Github` use

**Comment by Sanchitbajaj02** [comment]
![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/fa36474f-708d-4b0b-823a-906012314382)

## Markdown release having issue on production. 

validate all the checks and to replicate this, run `yarn build` and `yarn start` on your local machine
