### ISSUE TITLE
Feat: Help center form

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#102]
### What feature?

Currently, there is no way a person can contact the admin on the web app. To do that there will be a help center form where user can contact the admin if they required any help. 

### Add screenshots

This new feature will be connected to the help center menu.
![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/48399d57-f151-4994-8cab-8bdd1dee82a8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

**Comment by kolhesatish** [comment]
Can you assign this issue to me?

**Comment by Sanchitbajaj02** [comment]
> Can you assign this issue to me?

Sure. Assigned to you

**Comment by Archit5655** [comment]
I would like to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Archit5655 thanks for showing interest in this issue😊. Currently it is assigned to @kolhesatish but if I didn't get any response by tomorrow, I will assign this issue to you

**Comment by Sanchitbajaj02** [comment]
Hey @Archit5655 I didn't get the response, so assigning this to you 😊

**Comment by Archit5655** [comment]
I would like to know how do you want to be contacted for the users who need help.
I will need an email to which users can send their messages to that email directly through a form through resend API.

**Comment by Sanchitbajaj02** [comment]
> I will need an email to which users can send their messages to that email directly through a form through resend API.

Are you going to implement nodemailer for this or you are using some features of Appwrite?

**Comment by Archit5655** [comment]
can I use resend api? 
Read about It here-https://resend.com/docs/send-with-nextjs

**Comment by Sanchitbajaj02** [comment]
> can I use resend api? 
> Read about It here-https://resend.com/docs/send-with-nextjs

Yeah sure. It will be great. 
What you can do is create a structure of a collection which also stores the data response. 

Make sure to add resend api key and email to be environment variables and give a brief description in `.env.example`

**Comment by Sanchitbajaj02** [comment]
Hi @Archit5655 I am facing this issue while deploying the application.

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/8810d785-4dec-4304-b476-0964a74d6523)

Please make a PR fixing this issue. To replicate, what you can do is create a production build in your local using `yarn build` command.
