### ISSUE TITLE
Bug: Issue while trying to login 

### ISSUE THREAD

**Issue by Kanavmh** [Sanchitbajaj02/palettegram#104]
### What happened?

As a new user, attempted to register on the website. An error message (included in the screenshot) pops up.
After clicking on the Register Now button again, the second popup indicates the account has already been made.

Was able to login after entering details again in Login page. 
++Logging in the user right after registering puts forth a more streamlined logging in system.

(The screenshots were taken on the second attempt to login using another email which means the issue can be recreated.)

### Add screenshots

<img width="955" alt="Screenshot 2023-12-29 100300" src="https://github.com/Sanchitbajaj02/palettegram/assets/148423235/50123222-e3cd-4003-8157-b658ed2aa628">
<img width="955" alt="Screenshot 2023-12-29 100312" src="https://github.com/Sanchitbajaj02/palettegram/assets/148423235/1abce9a1-b045-401b-8c88-90d27ceab295">

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
> Was able to login after entering details again in Login page.
This is not the expected behavior of the application😅. It should tell you that you will receive an email for verification.

> ++Logging in the user right after registering puts forth a more streamlined logging in system.

Yeah I agree. Currently it isn't streamlined. Can you do that with the verification system as well?

**Comment by Sanchitbajaj02** [comment]
@Kanavmh as mentioned the same in issue #103, I took some help from the Appwrite support team to resolve this issue. It was related to the appwrite and not the application

**Comment by Kanavmh** [comment]
@Sanchitbajaj02 so can we consider this issue resolved now? The problem was on the third party's side.
