### ISSUE TITLE
Bug: can't register new user

### ISSUE THREAD

**Issue by Girishbari** [Sanchitbajaj02/palettegram#105]
### What happened?

The below problem is occurring while registering a new user, I guess there is problem with POST request 

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/be32077a-a615-4ec4-8b9c-fb79bb6c4e19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Girishbari** [comment]
If more information is provided I would like to work on this

**Comment by Sanchitbajaj02** [comment]
The same issue is already mentioned in issues: #103 and #104 so I can't assign this issue you and sadly have to mark this invalid
