### ISSUE TITLE
Feat: Implement of Forgot Password

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#106]
### What feature?

Addition of "Forgot Password" feature to facilitate password recovery for users. This feature will leverage `appwrite` authentication api for a seamless and secure password reset process.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Girishbari** [comment]
I could grab this one, right? @Sanchitbajaj02

**Comment by Sanchitbajaj02** [comment]
@Girishbari yeah sure. You can work on that. Assigned
