### ISSUE TITLE
Bug: Installation setup in local

### ISSUE THREAD

**Issue by Vidip-Ghosh** [Sanchitbajaj02/palettegram#111]
### What happened?

While setting up an environment in local, I am facing issues & getting error `Cannot find module`. 

### Add screenshots

<img width="1680" alt="Screenshot 2024-01-01 at 20 34 04" src="https://github.com/Sanchitbajaj02/palettegram/assets/91741581/1e13d94c-2a8a-4e67-83f1-2bfcb12891c6">

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Vidip-Ghosh which node version are you using currently?

**Comment by Vidip-Ghosh** [comment]
> Hi @Vidip-Ghosh which node version are you using currently?

18.15

**Comment by Sanchitbajaj02** [comment]
Let's try this. Run this below command and restart the terminal and start the project:

```bash
yarn add next@13.4.9
```

**Comment by Vidip-Ghosh** [comment]
> Let's try this. Run this below command and restart the terminal and start the project:
> 
> ```shell
> yarn add next@13.4.9
> ```

Still the same issue

**Comment by Vidip-Ghosh** [comment]
<img width="1477" alt="Screenshot 2024-01-02 at 11 11 56" src="https://github.com/Sanchitbajaj02/palettegram/assets/91741581/adbab82d-a499-46cb-b427-65b8286bcc9f">
After running the above command, it shows these

**Comment by Vidip-Ghosh** [comment]
Now working. 
I deleted & cloned into empty directory. So it worked.

**Comment by Sanchitbajaj02** [comment]
> Now working. 
> I deleted & cloned into empty directory. So it worked.

Thank you for informing. Closing this issue as well.
