### ISSUE TITLE
Feat: Delete post feature UI + API with context menu

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#115]
### What feature?

Currently, there is no way a user can delete their post. So, having a small menu which contains a delete post feature will be helpful to the users.

> [!IMPORTANT]
> Whoever works on this, they have to discuss about the soft delete or hard delete functionality.

### Add screenshots

Menu reference:

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/13bc8846-b054-4265-a482-9033c87cad73)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Girishbari** [comment]
almost done with the previous issue, I guess I could start working on it, so let's discuss  soft delete or hard delete functionality.

**Comment by Sanchitbajaj02** [comment]
@Girishbari I would appreciate you to please raise a PR first if you want to work on it 😊

**Comment by sumanjeet0012** [comment]
I want to work on this issue ,
assign it to me

**Comment by Girishbari** [comment]
raised the PR  #117

**Comment by Sanchitbajaj02** [comment]
> raised the PR #117

Sure, assigned to you.

**Comment by Sanchitbajaj02** [comment]
> I want to work on this issue , assign it to me

Sorry but @Girishbari already mentioned that he wants to work on this. You can take any other issues and if you find any difficulty, please let me know

**Comment by Girishbari** [comment]
I understand what hard and soft delete is, but how the backend is able to do both, could you provide a link or something
I went through this
[](https://appwrite.io/docs/references/cloud/client-web/databases#deleteDocument)
while reading through I understand that one can only delete a doc permanently

**Comment by Sanchitbajaj02** [comment]
Backend can support soft delete means I configured it for soft delete as well by adding a field for it😅. You don't have to worry about it.

**Comment by Sanchitbajaj02** [comment]
> hi, I created small poll on discord about it to get other devs perspective until then can you point to the file where you configured soft delete feature

I configured in appwrite, in the posts collection

**Comment by Sanchitbajaj02** [comment]
@Girishbari the issue is on hold due to appwrite changes

**Comment by Girishbari** [comment]
okay

**Comment by Girishbari** [comment]
the previous issue may not bother now , can I start to implement this feature again

**Comment by Sanchitbajaj02** [comment]
> the previous issue may not bother now , can I start to implement this feature again

Yeah, please take up this issue and get it resolved soon...
