### ISSUE TITLE
Style: Improving the ui of buttons

### ISSUE THREAD

**Issue by Archit5655** [Sanchitbajaj02/palettegram#118]
### What's the suggested design idea?

The buttons are too static I would like add some sort of hover effect that will improve the user experience .
![Screenshot 2024-01-03 173044](https://github.com/Sanchitbajaj02/palettegram/assets/112563353/e6bbd8e0-f517-428d-b0aa-c4697c758be3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Sure @Archit5655 it looks a bit too static. You can work on it but please remember that if you're using colors on many places, add them into `tailwind.config.js` so that it can be easily accessible through tailwind.

Assigned this issue to you 😊
