### ISSUE TITLE
Feat: Adding profile button in navbar

### ISSUE THREAD

**Issue by RahulGIT24** [Sanchitbajaj02/palettegram#120]
### What feature?

So When user gets logged in the Register button gets removed. When these buttons gets removed we can display feed and profile button so that user can easily navigate. I am taliking about the homepage navbar. Please add the SWOC tag.

### Add screenshots

![Screenshot from 2024-01-03 22-07-41](https://github.com/Sanchitbajaj02/palettegram/assets/103873656/25a4856e-cf1a-4c96-aae6-a4b5efb82bf9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi, @RahulGIT24 thanks for suggesting.

I would like to point out as well that **Start Your Jouney** button works the same as you suggested. Also, it will be written as **Checkout your feed** but it is not showing in your screenshot.

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/d08b9154-b89b-4b27-86bd-b75cfd8a24d1)


> When these buttons gets removed we can display feed and profile button so that user can easily navigate.

Yeah, you can add a profile button there which directly navigates the user to its profile page.
