### ISSUE TITLE
Bug: Single Post View Page by clicking on it

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#121]
### What happened?

Currently, when user click on the post, it will show 404 page but it should show a new page with the route:
`<base_url>/post/postId`

You have to make sure that if you click on the post, then only it will route the user to the post individual post.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by ani2607** [comment]
Can you please write the steps to be followed to reproduce it or some screenshot , as your issue is not clear . @Sanchitbajaj02

**Comment by Sanchitbajaj02** [comment]
### Steps to reproduce the issue:

- login to the app and visit the /feed page.
- click on any post.
- you will be redirected to a page which will say 404

**Comment by ani2607** [comment]
could you please assign this to me @Sanchitbajaj02 . I understood the issue.

**Comment by Sanchitbajaj02** [comment]
Sure, Assigned to you

**Comment by ani2607** [comment]
Do you have any design reference or I could go by my way @Sanchitbajaj02

**Comment by Sanchitbajaj02** [comment]
@ani2607 you can design in your way but keep in mind that the design will be in sync with the existing one. If you look into the code you might find the code for that page too.

**Comment by ani2607** [comment]
@Sanchitbajaj02 I solved this issue.Have a look at it  before I could make a pr and suggest me changes to be done if any . 

sample -> 
![Screenshot 2024-01-07 003308](https://github.com/Sanchitbajaj02/palettegram/assets/136100597/04613fbd-701a-4cce-99a3-f9f52d1e40ff)

**Comment by Sanchitbajaj02** [comment]
Please add all these features:

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/108b2425-b741-4d9c-be53-125c625afdc3)

It also has the trending post section which looks like the one on the /feed page

**Comment by ani2607** [comment]
@Sanchitbajaj02 do I need to add all the bottoms icons or I need to structure UI with the Ui given above.

**Comment by Sanchitbajaj02** [comment]
try to add just the icons with its features. Structure wise, you can decide yourself

**Comment by ani2607** [comment]
@Sanchitbajaj02 please check the pr.
