### ISSUE TITLE
Feat: Custom 404 Page

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#124]
### What feature?

Currently, application is using the default 404 page given by Next.js 13. 
There should be a customized 404 page with a header and footer of palettegram along with the route to go to home page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Archit5655** [comment]
I would like  to work on this issue

**Comment by Sanchitbajaj02** [comment]
@Archit5655 I think someone has already made the PR for this. If he follows the guidelines according to the project, I prefer his PR. You can take any other issue please if you want to😊

**Comment by Archit5655** [comment]
@Sanchitbajaj02  he just directly raised the PR even he is not assigned to the issue.
Please assign me I have the solution ready

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 he just directly raised the PR even he is not assigned to the issue. Please assign me I have the solution ready

Let's wait for his response for sometime. Till then I assigned you the other issue which you asked for it yesterday. Please complete that first.

**Comment by Sanchitbajaj02** [comment]
Hi @Archit5655, Since I didn't get the reply here or on the PR, I am assigning this issue to you and rejecting that PR.

**Comment by Sanchitbajaj02** [comment]
![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/84d5f6e1-de8b-486a-85fa-ffca0184f890)

@Archit5655 upon checking the deployment logs, this is the error, please resolve it.

**Comment by Archit5655** [comment]
I think this is fixed @Sanchitbajaj02

**Comment by Sanchitbajaj02** [comment]
> I think this is fixed @Sanchitbajaj02

Yeah, because I did few minutes ago
