### ISSUE TITLE
Bug: Hover effect on feed buttons not working properly

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#131]
### What happened?

As attached in the video below, when user hovers on gear icon, only the icon glows but the button looks normal. The gear icon should look like the ones adjacent to it.

### Add screenshots

<details>
<summary><b>Sample video</b></summary>
https://github.com/Sanchitbajaj02/palettegram/assets/55249639/da9f0482-8a7d-4187-b6ee-d24240a05377
</details>

### What browsers are you seeing the problem on?

Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by sumanjeet0012** [comment]
I want to work on this issue. Assign me.

**Comment by Sanchitbajaj02** [comment]
Hi @sumanjeet0012. Assigned to you
