### ISSUE TITLE
Bug: "Start your journey" button does not work for logged in users

### ISSUE THREAD

**Issue by sumanjeet0012** [Sanchitbajaj02/palettegram#134]
### What happened?

When a logged in user is on the home page and clicks the "Start your Journey" button, nothing happens. The button should redirect the user to the next relevant page or feed page of the website.

However, when a user who is not logged in clicks the "Start your Journey" button, they are correctly redirected to the registration page.

Steps to reproduce:

Log in to the website
Go to the home page (https://palettegram.vercel.app/)
Click the "Start your Journey" button

Expected result: User should be redirected to the next relevant page or feed page of the website.

Actual result: Nothing happens when the button is clicked. No redirection or error.

The button works as expected for non-logged in users, taking them to the registration page. But it does not work for logged in users.

### Add screenshots

https://github.com/Sanchitbajaj02/palettegram/assets/78401409/4b56bca6-edb1-4ac0-b9ea-3a4321e56f42

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
@sumanjeet0012 yeah it is occurring for sometime now. It is configured that if user is logged in, a button with Checkout your feed will be visible. Assigned to you

**Comment by Sanchitbajaj02** [comment]
@sumanjeet0012 please complete the changes that I added on PR #135 before working on any other issues. I am not going to assign new ones if you didn't complete your previous ones.
