### ISSUE TITLE
Feat: Sign in with google Button

### ISSUE THREAD

**Issue by sumanjeet0012** [Sanchitbajaj02/palettegram#139]
### What feature?

There should be an sign in with google button so that users can visit this website easily without manually signing up in the website.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/78401409/96d8b132-97c4-4063-8e9f-dee0a132629e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Yeah idea is good. You can use the google OAuth2.0 given by Appwrite. Assigned to you
