### ISSUE TITLE
Bug: Loading issue on Homepage

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#140]
### What happened?

On homepage, due to loading is implemented for full screen, it is showing the following result. To fix that, handle the loading for page and component seperately.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/27744b2e-41c0-4d3b-9018-9d26680b5b24)

### What browsers are you seeing the problem on?

Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Sure @ani2607 assigned this issue to you

**Comment by ani2607** [comment]
@Sanchitbajaj02 should I make navbar and page component(copy from the home page) in home folder and render those with suspense and lazy loading . As I couldn't figure out any other way.

**Comment by Sanchitbajaj02** [comment]
Is it possible to parse the width and height in loader component or maybe move that height component in the loader itself

**Comment by ani2607** [comment]
> Is it possible to parse the width and height in loader component or maybe move that height component in the loader itself
parsing is not possible as loader component is at the root directory and prop couldn't be send from lower heirarchy component.

**Comment by ani2607** [comment]
I think there could be two ways to handle:-
1) I'll make the height value at loader component to zero as it would solve the error of home page but while loading other pages the loader would be at the extreme top of page.
2) For everypage I define the layout of that page and render the loader .

**Comment by Sanchitbajaj02** [comment]
@ani2607 you idea is good but do we actually need all extra layout.tsx files just to render a loader. Can't we do that by parsing a prop in loading component something like a boolean variable which gives it a height.
Do a research in the above approach and let me know because the 1st thing you suggested, it was added previously.

**Comment by thevirengarg** [comment]
@ani2607 What's the progress on this issue?

**Comment by ani2607** [comment]
> @ani2607 What's the progress on this issue?

reviewing into it.

**Comment by Sanchitbajaj02** [comment]
@ani2607 unassigning this to you since you didn't gave any update for over a week

**Comment by Girishbari** [comment]
assign me

**Comment by Sanchitbajaj02** [comment]
@Girishbari assign to you
