### ISSUE TITLE
Feat: Seperate Loading Skeleton for posts

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#144]
### What feature?

Currently posts does not have a separate skeleton loading animation. Also, the `/feed` shows empty space when data is loading for first time.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by IrfanshaikH-7** [comment]
I'll work on this ...

**Comment by Sanchitbajaj02** [comment]
Sure you can take this issue. Assigned

**Comment by Sanchitbajaj02** [comment]
@IrfanshaikH-7 since you have issues already assigned to unassigning

**Comment by Ayush-2301** [comment]
@Sanchitbajaj02  please assign this issue to me under iwoc2024

**Comment by Sanchitbajaj02** [comment]
sure @Ayush-2301, assigned to you

**Comment by Sanchitbajaj02** [comment]
@Ayush-2301 update the progress by today or you will get unassigned in 48 hours

**Comment by Girishbari** [comment]
nobody seems to be taking, then assign me

**Comment by Sanchitbajaj02** [comment]
> nobody seems to be taking, then assign me

@Girishbari assigned to you
