### ISSUE TITLE
Feat: User profile page (User Interface)

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#145]
### What is the feature enhancement?

Currently, the user profile page is showing it's posts and the name. Can we align the UI to a more standard UI like the Linkedin Profile page or the Twitter Profile page

This issue is related to the frontend and redux side of the project.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/7250cd25-e6eb-4586-a679-acdac6bc7219)

The PR of this issue will be successfully merged if it passes these parameters

- [ ] profile Avatar
- [ ] profile Banner
- [ ] user's full name
- [ ] user's username
- [ ] user's bio
- [ ] user's website link / any link (only 1)
- [ ] number of posts posted

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by IrfanshaikH-7** [comment]
I'll work on this!

**Comment by Sanchitbajaj02** [comment]
> ### I'll work on this!
> As I'm the one assigned to the Skeleton of the posts, I should do this whole thing together!
> 
> As I just looked into it, user don't have that many fields. we should first implement that. before moving onto profile page

Already assigned 2 issues, can't assign more

**Comment by Ayush-2301** [comment]
Hello @Sanchitbajaj02 please assign this issue to me under iwoc2024

**Comment by IrfanshaikH-7** [comment]
I'm working on it. bro
Would you like to work on like, comment , share or bookmark feature implementations
