### ISSUE TITLE
Feat: User profile page (Backend)

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#146]
### What is the feature enhancement?

Currently, the user profile page is showing it's posts and the name. Can we align the UI to a more standard UI like the Linkedin Profile page or the Twitter Profile page.

This issue is related to the backend and API handling side of the project.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/7250cd25-e6eb-4586-a679-acdac6bc7219)

The PR of this issue will be successfully merged if it passes these parameters

- [ ] a proper api handled backend
- [ ] no redundency in the code
- [ ] have a descriptive architecture approach mentioned in the PR to setup in the Appwrite
- [ ] proper handling of types and type guard should be present

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

**Comment by Vidip-Ghosh** [comment]
Please assign this issue to me.

**Comment by Sanchitbajaj02** [comment]
> Please assign this issue to me. 

Assigning this to you

**Comment by Girishbari** [comment]
Assign me

**Comment by Sanchitbajaj02** [comment]
@Girishbari assigned to you

**Comment by Sanchitbajaj02** [comment]
@Girishbari what is the update on this? please inform within 24 hrs

**Comment by Girishbari** [comment]
Yeah, I was inactive for days due to some unforeseen, I will try for pull request on today itself
