### ISSUE TITLE
Feat: Appwrite schema migration script

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#148]
### What feature?

Currently many contributors are facing the issue to setup the application so a common credentials have been provided to work on. But to optimally test and experience the power of Appwrite a schema file will be provided for the users to work and deploy the application to their own account.

> [!NOTE] 
Documentation for the same will also be mentioned in the `docs/appwrite.md` file so that contributors can easily follow the steps.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by iMADi-ARCH** [comment]
I can do this but I will need your help getting the current state of the appwrite database as I don't have access.

1. First install appwrite cli - https://appwrite.io/docs/tooling/command-line/installation
```bash
npm install -g appwrite-cli
```

2. Login with your email and password
```bash
appwrite login
```

3. Generate `appwrite.json` file:
```bash
appwrite init project
appwrite init collection
appwrite init teams
```
select appropriate options when prompted.
then maybe send the appwrite.json file to me directly on discord - (username: `aditya.nandan`) or push it to the repo.

Then I can add proper documentation to make sure contributors can migrate the database to their own appwrite instances.

**Comment by Sanchitbajaj02** [comment]
@iMADi-ARCH this feature I've already explored. Is there a way to also migrate and backup the collections?

**Comment by iMADi-ARCH** [comment]
@Sanchitbajaj02 we can setup a github action which will automatically update the production database with the proper collection schema based on the `appwrite.json` file.
I have done this with supabase, and the process seems similar.

What kind of backup you mean?
