### ISSUE TITLE
Bug: Side contents isn't sticky on scroll

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#149]
### What happened?

When user scroll down to the post, the left side user button and bookmark button as well as the right side trending section should be static and does not scroll up with the scrolling of content.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by yashi-15** [comment]
I would like to work on this issue, please assign it to me under SWOC. Thankyou!

**Comment by Sanchitbajaj02** [comment]
Hi @yashi-15 you can take up the issue. Assigned
