### ISSUE TITLE
Style: Implement account icons instead of setting icon

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#150]
### What's the suggested design idea?

If a user wants to visit the profile page, they have to click on the gear icon to go there, but it is not looking good. The task is to add the user/account icon. Current design given below.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/687ca5a1-663a-4ed8-91c3-8ef55190f766)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by sumanjeet0012** [comment]
assign me

**Comment by Sanchitbajaj02** [comment]
> assign me

I can't since you haven't finish your previous tasks

**Comment by Priyanshu1129** [comment]
I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
> > assign me
> 
> I will not since you haven't finish your previous tasks. Please finish the tasks in hand then I will merge this

Since your previous PR is resolved, I am assigning this to you...

**Comment by Sanchitbajaj02** [comment]
> I want to work on this issue.

Hi @Priyanshu1129, the issue is already taken care of by @sumanjeet0012. You can explore more issues which aligns with your skills, or you can create one.

**Comment by Priyanshu1129** [comment]
Okay
