### ISSUE TITLE
Feat: Image upload lossless compression

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#151]
### What feature?

Currently there is no validation or image compression algorithm or library has been implement to check the image size and type. The supported mime type should be `.jpg, .jpeg, .png or .svg`. There should also be a limit of 1 MB to upload the image.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by vrun1208** [comment]
@Sanchitbajaj02 If no one is working, I'm willing to work on this

**Comment by Sanchitbajaj02** [comment]
Yeah @vrun1208 you can work on this issue. Assigned to you
