### ISSUE TITLE
Feat: Confetti animation on verified page

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#152]
### What feature?

When user visits on `/verify` page after clicking on verification link, a confetti animation will be shown to them representing that they are successfully verified.

**You can use any confetti library but it should not be large**

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Kanavmh** [comment]
Hey, I'd like to work on this. I'm open to others also working on this since I'm new to the language if that's possible!

**Comment by vrun1208** [comment]
Hi @Sanchitbajaj02 , I want to work on this issue!!

**Comment by Sanchitbajaj02** [comment]
> Hey, I'd like to work on this. I'm open to others also working on this since I'm new to the language if that's possible!

Sure you can work on it. Explore the language and its libraries and let me know if you need any help😊

**Comment by Sanchitbajaj02** [comment]
> Hi @Sanchitbajaj02 , I want to work on this issue!!

Hi @vrun1208, sorry you're a little late. You can explore more issues or create new ones 😊

**Comment by vrun1208** [comment]
okay sure! also @Kanavmh feel free to ask if needed 🚀

**Comment by thevirengarg** [comment]
@Kanavmh Are you still working on this issue?

**Comment by Niharika0104** [comment]
@Sanchitbajaj02 I would like to work on this issue

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 I would like to work on this issue

Sure, assigned to you
