### ISSUE TITLE
Feat: Profile post sharing option

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#153]
### What feature?

There should be an option to share the posts on other social media platforms. The UI of this feature is already developed. As a contributor, your task is to implement a feature to share on multiple social media apps. 
Please find below the reference photo from hashnode.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/b05c09fd-3eaf-4b1d-ae30-ffce426e81fc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by DaSeeker67** [comment]
hello @Sanchitbajaj02  can you assign this to me

**Comment by Sanchitbajaj02** [comment]
> hello @Sanchitbajaj02 can you assign this to me

I have already assigned you an issue so please finish that first to get assigned on this

**Comment by rishicds** [comment]
Hello, I'd like to work on this please assign it to me under SWOC'24 :)

**Comment by Sanchitbajaj02** [comment]
Hi @rishicds, assigning this issue to you

**Comment by thevirengarg** [comment]
@rishicds What's the progress on this issue??

**Comment by rishicds** [comment]
Hello, I had exams that's why I was unable to complete it, if possible please reassign it to me I'll do it in a day or two @Sanchitbajaj02 @thevirengarg

**Comment by thevirengarg** [comment]
@rishicds Okay i will re-assign you this issue, but you only have 48 hours to complete it.

**Comment by rishicds** [comment]
On it @thevirengarg
