### ISSUE TITLE
Feat: Random avatar generator for profiles

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#154]
### What feature?

Currently there is no way to generate a avatar (profile image). So to add this feature when user gets registered into database, a random avatar should be added in as avatar.

You can choose any light weight library to generate avatar. I prefer to use https://boringavatars.com/ since it matches with the ideas of our project.

The avatars will be saved in Appwrite bucket.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by DaSeeker67** [comment]
@Sanchitbajaj02  can i get this issue , i will be doing this 1. Integrate Boring Avatars library for lightweight avatar generation.
2. Implement the avatar generation process during user registration.
3. Ensure seamless saving of avatars in the Appwrite bucket.

**Comment by Sanchitbajaj02** [comment]
There is a last step that is to save the bucket link into the user's profile. 

Please proceed with approach that you have mentioned and let me know if you stuck somewhere

**Comment by DaSeeker67** [comment]
@Sanchitbajaj02  sure sir

**Comment by DaSeeker67** [comment]
Hello @Sanchitbajaj02  sir can i get the credentials for the appwrite ,

**Comment by Sanchitbajaj02** [comment]
Hi @DaSeeker67. Marked the credentials in the palettegram channel, you can check that out

**Comment by DaSeeker67** [comment]
ok sir got it

**Comment by DaSeeker67** [comment]
> There is a last step that is to save the bucket link into the user's profile.
> 
> Please proceed with approach that you have mentioned and let me know if you stuck somewhere
@Sanchitbajaj02 
hello sir , I had imported the library and generated the random in the auth.api.ts in the saveDataToDatabas point so it will save the generated link for the logo in the data base , now I'm stuck like do I have to update the login page or there is some user logo global that I can update by  fetching the user data , please help

**Comment by Sanchitbajaj02** [comment]
>generated the random in the auth.api.ts in the saveDataToDatabas

I prefer you to make a seperate function in a seperate file and import that function there which returns the url string

> now I'm stuck like do I have to update the login page or there is some user logo global that I can update by fetching the user data , please help

I don't think we need to show the user their avatar on login page. It's avatar is visible only on the profile page

**Comment by thevirengarg** [comment]
@DaSeeker67 What's the progress on this issue?

**Comment by DaSeeker67** [comment]
Will make pr tonight

**Comment by Sanchitbajaj02** [comment]
@DaSeeker67 Please update your pull request with the requested changes. I will close this pull request and unassign you with this issue in 48 hours

**Comment by Manishak798** [comment]
@DaSeeker67 Any Updates regarding your work?

**Comment by DaSeeker67** [comment]
@Manishak798 I am little busy with my college work will figure out the issue and work on it tonight

**Comment by Sanchitbajaj02** [comment]
> @Manishak798 I am little busy with my college work will figure out the issue and work on it tonight

Sure, take your time, just update us from time to time

**Comment by DaSeeker67** [comment]
i don't understand the problem, i had checked and once the avatar link is generated it will not change so I guess there's no issue in the avatar generation

**Comment by Sanchitbajaj02** [comment]
@DaSeeker67 there is no issue related to the code and I have checked it as well. The problem is that your PR is having merge conflicts. Please resolve them and raise a PR, I will merge it

**Comment by Girishbari** [comment]
assign me

**Comment by Sanchitbajaj02** [comment]
> assign me

The PR is already assigned and the required changes have already been made. If possible could you help the person responsible for this PR to solve the merge conflicts

**Comment by Girishbari** [comment]
I see currently there is no assignee
