### ISSUE TITLE
Style: Responsiveness on feed page

### ISSUE THREAD

**Issue by IrfanshaikH-7** [Sanchitbajaj02/palettegram#157]
### What's the suggested design idea?

**The UI is not so responsive on mobile to small devices.**

The UI should be centered. 
- 

### Add screenshots

![Screenshot 2024-01-08 192119](https://github.com/Sanchitbajaj02/palettegram/assets/124655192/4ab83cdc-f7ff-4c3b-bc01-884cfd3fc12b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by IrfanshaikH-7** [comment]
Could you please assign this to be!. I'm already done with the improvements

**Comment by Sanchitbajaj02** [comment]
Sure @IrfanshaikH-7 assigned this issue to you
