### ISSUE TITLE
Bug: Users aren't able to create more than one post.

### ISSUE THREAD

**Issue by IrfanshaikH-7** [Sanchitbajaj02/palettegram#158]
### A User is not able to create multiple posts.
**These issue is associated with _Appwrite_ ! below is a image of error message**

![Screenshot 2024-01-08 160346](https://github.com/Sanchitbajaj02/palettegram/assets/124655192/df4f54e0-6298-43fe-b495-a80f5a9bca0c)

More on this issue:

- When creating the post created message is showing Successful

Clues -

- There seem to be conflict with collection ID

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by IrfanshaikH-7** [comment]
@Sanchitbajaj02  Ping me on Discord -> I think I found the potential solution for this .

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 Ping me on Discord -> I think I found the potential solution for this.

I will but please also mention the solution here as well for future visitors

**Comment by Sanchitbajaj02** [comment]
## The issue has been resolved.

The issue was related to the indexes added into the appwrite collection. Upon removing them, it is resolved
