### ISSUE TITLE
Bug: Like count resets to zero on reloading the page

### ISSUE THREAD

**Issue by Rakshit358** [Sanchitbajaj02/palettegram#160]
### What happened?

On reloading the page it resets the like count to zero.

https://github.com/Sanchitbajaj02/palettegram/assets/117663522/c8dd2151-f0e1-4265-971a-8f04646f84b4

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Rakshit358 thanks for informing the issue but like count issue is already added. Please refer #92 

The entire like functionality has to be created. Closing this issue since it is a duplicate. If you want, you can take that issue 😊

**Comment by Rakshit358** [comment]
Sorry I forgot to recheck....
Thanks for assigning,will try to resolve it as soon as possible.
