### ISSUE TITLE
Bug: The Content trims for more than 500 characters

### ISSUE THREAD

**Issue by kherkatary** [Sanchitbajaj02/palettegram#161]
### What happened?

# BUG: 
- If we post large contents, then the post container trims the content to 500 characters

# Resolve Suggestion
- We can implement a counter to tell the user before hand so that he can limit his content to 500 chacters or less.

### Add screenshots

![pallete_issue_count_char](https://github.com/Sanchitbajaj02/palettegram/assets/97865752/0b7074c8-3c06-4e87-80a0-dc7d90d8b2c9)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @kherkatary, your idea is great and thanks for informing as well. You can work on this issue.
