### ISSUE TITLE
Feat: Ability to post by pressing Ctrl + Enter

### ISSUE THREAD

**Issue by iMADi-ARCH** [Sanchitbajaj02/palettegram#166]
### What feature?

As a user I would like to be able to create posts by pressing the universal hotkey `Ctrl + Enter` while the text input is focused.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
The feature is great but does this feature works with the markdown editors like the one used in github?
Also check the compatibility since the markdown editor isn't implemented

**Comment by iMADi-ARCH** [comment]
https://docs.github.com/en/get-started/accessibility/keyboard-shortcuts#comments
![image](https://github.com/Sanchitbajaj02/palettegram/assets/61308761/bae34af2-0ba0-4508-beed-fef76e4844a4)

`Ctrl + Enter` hotkey is used to submit a comment here on github as well.

**Comment by Sanchitbajaj02** [comment]
Sure, assigned to you
