### ISSUE TITLE
Docs: requirement Table of content

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#167]
### What you want to add in the documentation?

Contributors has to scroll down to the bottom of the screen for the docs access so there should be a table of content to help the contributors to navigate into the readme file

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by raysofani** [comment]
@Sanchitbajaj02  Please assign me this issue under IWOC2024.

**Comment by Sanchitbajaj02** [comment]
@raysofani assigned

**Comment by raysofani** [comment]
@Sanchitbajaj02 can you tell in brief  about what all documents you want in table of content?

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 can you tell in brief about what all documents you want in table of content?

You can take up all the subheadings in the README.md file + all the files present in the docs folder

**Comment by thevirengarg** [comment]
@raysofani if you don't make a pull request for this issue within 24 hours, i will unassign you this issue.

**Comment by SpaciousCoder78** [comment]
Can you assign this task to me?

**Comment by Sanchitbajaj02** [comment]
> Can you assign this task to me under gssoc 24?

Sure, assign to you

**Comment by Sanchitbajaj02** [comment]
## A bug has been detected that was missed

On clicking on the menu, the user will redirected to the forked repo. Please fix that

**Comment by SpaciousCoder78** [comment]
I shall work on that immediately

**Comment by SpaciousCoder78** [comment]
Requesting to close the issue since the PR has been merged
