### ISSUE TITLE
Style: UI improvement for user page.

### ISSUE THREAD

**Issue by IrfanshaikH-7** [Sanchitbajaj02/palettegram#168]
### What's the suggested design idea?

**The posts are rendering without a proper format neither they are responsive!**

**Solution :** 
        We can keep the posts **vertically scrollable** just like in feed pages in sorted order - having **right side for the bookmarks and recommendations** and **left for account setting and other profile related stuff**

If you have any additional things to add or a design reference! they are welcomed!

> _Could you please assign me this. -_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Will assign you this issue when you make the PR of issue in hand

**Comment by IrfanshaikH-7** [comment]
I'm not actually assigned to any issue : Assign me the issue #169 as I have already resolved it - I'll PR then issue me this one.

**Comment by Sanchitbajaj02** [comment]
ok sure

**Comment by ani2607** [comment]
@IrfanshaikH-7 Are you working on  user/bookmarks url page or not . If not please let me know.

**Comment by IrfanshaikH-7** [comment]
> @IrfanshaikH-7 Are you working on user/bookmarks url page or not . If not please let me know.

No - I'm woking on user/userid

**Comment by ani2607** [comment]
> > @IrfanshaikH-7 Are you working on user/bookmarks url page or not . If not please let me know.
> 
> No - I'm woking on user/userid! I'm not sure if is there is any issue related to bookmarks ! check if its not there , and Create one and let admin assign it to you

yaa! Thought of implementing it into a grid but it seems pretty good.
