### ISSUE TITLE
Bug:  User Page rendering "currentUser"'s details rather than the posts owners 

### ISSUE THREAD

**Issue by IrfanshaikH-7** [Sanchitbajaj02/palettegram#169]
### The Bug is: 
Upon clicking on a profile photo on a post  - > User Page is rendering currently logging in user's details _(i.e., self details,)_ 
 rather than rendering posts owner's details 

 **_Note:  The posts are rendering correctly the only issue is with the user details._**

※ Currently we are fetching currentUser where it should be the user whose the post belongs to 

This here is the problem code that is fetching the currentUser
You can find this snippet at 

> components > pages > users > index

![curr](https://github.com/Sanchitbajaj02/palettegram/assets/124655192/36a5efa8-884a-4b4a-a793-465c1640280c)

 
Assign this to me -As I already found the fix to it, I'll PR

- [X] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
assigned the issue

**Comment by IrfanshaikH-7** [comment]
I fixed the issue : 
 But its only working for old users - maybe something has to do with verify -once that resolves  it should work fine
 : For that - Could you please delete my accounts that I dm you. for me to reregister

**Comment by Sanchitbajaj02** [comment]
Yeah appwrite has some issues. I will update when it fixes

**Comment by Sanchitbajaj02** [comment]
@IrfanshaikH-7 You can work on it since appwrite functionality is fixed

**Comment by IrfanshaikH-7** [comment]
Sure I'll work
