### ISSUE TITLE
Feat: detailed footer section

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#172]
### What feature?

Currently the application has only copyright footer. But a footer with detailed information will be great for navigations.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 can you please assign this issue to me .I would love to work on this.

Sure @YASH-YADAV-dynamo assigned this issue to you

**Comment by thevirengarg** [comment]
@YASH-YADAV-dynamo I am un-assigning you this issue its been 5 days you haven't updated with the progress.

**Comment by thevirengarg** [comment]
@mansi1309 Do you want to work on this issue. Now its available for you to work.

**Comment by mansi1309** [comment]
@thevirengarg okay

**Comment by Sanchitbajaj02** [comment]
@mansi1309 assigned this to you. Please try to raise a PR in 2-3 days or you will get unassigned

**Comment by thevirengarg** [comment]
@mansi1309 What's the progress on this issue? If you don't raise a PR in 24 hours I will unassign it.

**Comment by monoMonu** [comment]
@thevirengarg I would like to work on this issue,please assign this to me

**Comment by Sanchitbajaj02** [comment]
@monoMonu assigned to you, just inform are you associated with SWOC or IWOC

**Comment by monoMonu** [comment]
> @monoMonu assigned to you, just inform are you associated with SWOC or IWOC

SWOC

**Comment by monoMonu** [comment]
@Sanchitbajaj02 what are the things to be added in footer?
Nav bar navigations and ?

**Comment by Sanchitbajaj02** [comment]
@monoMonu sorry for the delay from my side, You can take reference from below screenshot

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/e1edf838-7981-4452-927d-50990012ff72)

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 
> Is it okay? It is responsive as well
> 
> ![Screenshot 2024-02-07 002026](https://github.com/Sanchitbajaj02/palettegram/assets/142221687/970b17c7-afe3-49b9-9347-9cf488fc4b30)
> 

Looks amazing 🤩. Just a few things to fix and take your time to make it responsive.

1. Remove the shadow on the logo
2. Make the menu items a bit lighter

**Comment by monoMonu** [comment]
I'm having this issue while committing
Please help to solve this 

![Screenshot 2024-02-07 220719](https://github.com/Sanchitbajaj02/palettegram/assets/142221687/a11b30ce-6df5-4617-8c34-e5bbccc11d40)

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 please review

A little change, when I was typing I mistype, darker instead of lighter😅. Can you make the menu items darker?

**Comment by Sanchitbajaj02** [comment]
> I'm having this issue while committing Please help to solve this
> 
> ![Screenshot 2024-02-07 220719](https://private-user-images.githubusercontent.com/142221687/303060830-a11b30ce-6df5-4617-8c34-e5bbccc11d40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjQ3ODMsIm5iZiI6MTcwNzMyNDQ4MywicGF0aCI6Ii8xNDIyMjE2ODcvMzAzMDYwODMwLWExMWIzMGNlLTZkZjUtNDYxNy04YzM0LWU1YmJjY2MxMWQ0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwN1QxNjQ4MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzk4NjYzNjNjMmQzZmQwMDdiOWMyMzE0MTk5MzRmZjk2NzVjN2I0NzdiNjlmNTIzNzc0MzJmNjRjOTM1ZjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dcbs7MLZ4bUxrAAPckLNwqrtnRQvpqITLJn0XxjFBhc)

You can follow the steps mentioned in discussion: #226

**Comment by monoMonu** [comment]
@Sanchitbajaj02 Now, I am getting this

![Screenshot 2024-02-07 225100](https://github.com/Sanchitbajaj02/palettegram/assets/142221687/f611b755-6903-4ec1-9b81-7fb03e6f7bf5)

**Comment by Sanchitbajaj02** [comment]
@monoMonu please follow the commit guidelines mentioned in docs/commitlint.md
