### ISSUE TITLE
Bug: logout function does not clear userID

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#175]
### What happened?

currently user can't log out because cookies are not clearing

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by IamSudhir-Kumar** [comment]
Hey, @Sanchitbajaj02 I am a contributor in SWOC S4 . Can you assign me this issue I want to work on this challenging issue..!

**Comment by Sanchitbajaj02** [comment]
@IamSudhir-Kumar assigned the issue to you

**Comment by Girishbari** [comment]
this was sorted during last meet ..? @Sanchitbajaj02

**Comment by Sanchitbajaj02** [comment]
> this was sorted during last meet ..? @Sanchitbajaj02

Yeah but not implemented, so I assigned him

**Comment by Sanchitbajaj02** [comment]
Hi @IamSudhir-Kumar I have requested changes on your Pull Request but you didn't respond till now. If you don't respond in next 24 hours, you PR will be rejected.

@Girishbari you can take this issue if he didn't respond in next 24 hours

**Comment by IamSudhir-Kumar** [comment]
I believe I've reached a point where I can't make additional improvements. @Girishbari , I recommend proceeding with this issue. Recognizing areas where I can enhance my skills, I've decided to upskill and will return better equipped in the future.

**Comment by Sanchitbajaj02** [comment]
@IamSudhir-Kumar that's so much great. When @Girishbari will raise the PR you will get to know where you were missing. 

The best way to practice and upskill is to try and understand the PRs that got merged or raised. And if you get stuck or want to understand anything related to them, just ping on SWOC Palettegram discord group or DM me personally😊
