### ISSUE TITLE
Bug: Users are able to access feed  without verifying

### ISSUE THREAD

**Issue by IrfanshaikH-7** [Sanchitbajaj02/palettegram#178]
### Currently 

- users are able to access feed page make posts and all without verifying there emails,
- after submitting register form users are redirected to any page feeling like a error
- causing user data to not update in Database

### Expected:
- Users shouldn't be allowed to visit /feed unverified and redirecting them to waiting page asking them to verify there by clicking on the link sent to their respective emails
- after registering users should be redirected to verify waiting page asking them the same

**proposing Solution:**

- Can add a condition checking verified field, if not verified redirecting them to waiting page
- same can be done with register form submit
- and once user is verified, we can redirect him to /feed

> **Note: This solution will require resetting auth users and user DB. After implementing it...**

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
> after submitting register form users are redirected to any page feeling like an error.

I am not able to replicate that.

> causing user data to not update in Database.

Currently the database is designed so that, the accountId of user has to be present in users table to insert the data in posts. If not implemented correctly, you can work on that.

> and once user is verified, we can redirect him to `/feed`.

> [!IMPORTANT]
> User has to redirect to the `/verify` page first because according to the current system, user details have been updated on verify page.

**Comment by IrfanshaikH-7** [comment]
> > after submitting register form users are redirected to any page feeling like an error.

> Currently the database is designed so that, the accountId of user has to be present in users table to insert the data in posts. If not implemented correctly, you can work on that.
> 
> > and once user is verified, we can redirect him to `/feed`.
> 


### 
I'm not sure if we are on the same page here but   :

lets see - 
1. once you submit register form - are you experiencing any redirects ?? ---it's no for me
2.  you able to access /feed page without verifying on by clicking on the link sent to your email - its yes for me

Note: we are creating user document in verify function - and that is being called after user authentication 
And its not related to posts Tho!
 **If I'm explaining it correctly - if user doesn't click on verify link sent to their emails users won't get added to database**

**Comment by Sanchitbajaj02** [comment]
@IrfanshaikH-7 assigning this to you. Please research on it and give a proper solution for this issue
