### ISSUE TITLE
Bug: Cannot create comments to newly created posts

### ISSUE THREAD

**Issue by iMADi-ARCH** [Sanchitbajaj02/palettegram#183]
### What happened?

To reproduce - 
1. create a new post
2. try adding a comment to that post
3. an error will be raised (see screenshot).

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/61308761/3910f4d4-aec2-4390-aff0-b2ec9bf2818f)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Brave, Other

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Girishbari** [comment]
update your branch or maybe reset your project, I did not encountered it

**Comment by Sanchitbajaj02** [comment]
@iMADi-ARCH Try to reproduce this issue and let me know. If you face any problems, I will assign this issue to you.

**Comment by thevirengarg** [comment]
@iMADi-ARCH Did you encounter this issue again? Else I will close this issue.

**Comment by Sanchitbajaj02** [comment]
@iMADi-ARCH can you tell me the steps to replicate this issue?
