### ISSUE TITLE
Feat:  need to render comments

### ISSUE THREAD

**Issue by Girishbari** [Sanchitbajaj02/palettegram#191]
### What feature?

currently one can post comment and can get notified that comment is added but there is no way a user can see comments 

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/a16a5ff0-4b07-48b8-b343-974a91b0d5f8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
@Girishbari User post visibility should be on `/post/postId`. On `/feed` user can not see the comments. You can implement the functionality on `/post/postId`.

Assigned to you.

**Comment by Sanchitbajaj02** [comment]
@Girishbari what is the progress on this issue?

**Comment by Girishbari** [comment]
had some work, will try  for a pull request tonight

**Comment by Girishbari** [comment]
feat: #217
