### ISSUE TITLE
Feat: appwrite-gen implement indexes

### ISSUE THREAD

**Issue by iMADi-ARCH** [Sanchitbajaj02/palettegram#193]
### What feature?

To be able to create indexes from the ui and save them to `appwrite-gen/schema.json` by running `yarn schema:generate`.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
@iMADi-ARCH assigned the issue to you
