### ISSUE TITLE
Feat: setup basic e2e tests

### ISSUE THREAD

**Issue by adityanandanx** [Sanchitbajaj02/palettegram#195]
### What feature?

Setup some e2e tests to start with including (but not limited to) - 
- registration and login flow
- post creation

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @iMADi-ARCH currently didn't think of the scope of testing frameworks. Will update you once my research is finished.
