### ISSUE TITLE
bug: Form Validation 

### ISSUE THREAD

**Issue by Sanjana787** [Sanchitbajaj02/palettegram#197]
### What happened?

the user registration form in the project accepts numerical in place of full name whereas the expected input is always in characters.

### Add screenshots

![5](https://github.com/Sanchitbajaj02/palettegram/assets/141259407/8461fbb5-13c2-4f81-a49e-18ed3520e47f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanjana787** [comment]
@Sanchitbajaj02 please assign this issue to me.

**Comment by Sanchitbajaj02** [comment]
Yeah, I didn't noticed this until now. Please take up and fix this issue.

**Comment by Manishak798** [comment]
@Sanjana787 Any updates on your work?

**Comment by thevirengarg** [comment]
@Sanjana787 I am unassigning you this issue, you made no progress to it.

**Comment by Sanjana787** [comment]
I am sorry for the delay @Manishak798, @Sanchitbajaj02  and @thevirengarg.
 if possible please reassign this issue to me.

**Comment by Sanchitbajaj02** [comment]
@Sanjana787 I am only assigning again but I need a PR in 24 hours or else I will assign you

**Comment by monoMonu** [comment]
@Sanchitbajaj02 I would like to work on this issue

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 I would like to work on this issue

Assigned to you

**Comment by monoMonu** [comment]
Currently, Password validation is considering only two characters as special characters, reducing the capability of forming a strong password.

@Sanchitbajaj02 Should I change it to accept other special characters as well?

**Comment by monoMonu** [comment]
But how would the user get to know that they can only use those 2 special characters ?

I was trying to register but couldn't register because I was using other special characters in my password. and it was showing the same alert that "Oops!, Password must contain a character, a number and a special character", even though I was using correct combination as per the alert message. I think it would be better to take other special characters as well. What do you say?

**Comment by Sanchitbajaj02** [comment]
> only use those 2 special characters?

We can provide a small text under the password field.

**Comment by Sanchitbajaj02** [comment]
@monoMonu update the pr for merge. It is reviewed but there are merge conflicts that needs to be resolved
