### ISSUE TITLE
Style: Adding footer section

### ISSUE THREAD

**Issue by mansi1309** [Sanchitbajaj02/palettegram#198]
### What's the suggested design idea?

I want to add footer section with famous names and logo and link of facebook,github,linkdin etc.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/133951716/675d6364-c582-4c66-84da-5da518ca8b6d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi, @mansi1309, sorry to let you know that this issue is already taken. Refer issue #172.
You can take other issues or create new one.

> [!NOTE]
> If the assigned person didn't respond in 48 hours, I will assign the issue to you. Just comment under that issue to get assigned.
