### ISSUE TITLE
Bug: Can't able to upload new Post

### ISSUE THREAD

**Issue by Girishbari** [Sanchitbajaj02/palettegram#200]
### What happened?

@Sanchitbajaj02 , I guess this could be done from your side, the database would need to add postImages attribute

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/57be16e5-6260-4066-91dd-3ceb42d6744b)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
The issue is there because after restructuring the db, postImage is converted to postImages
