### ISSUE TITLE
Style: Help Center form UI

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#205]
### What's the suggested design idea?

Currently the help center (contact us) page is looking bland. So maybe we should sync the ui with the one used in register/login page.

## Current UI

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/fef1b18b-f598-4a05-a5db-cecd6b62f508)

## Expected UI

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/ae53a13f-8d60-4de2-9139-392d2150d78c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by anirbanmajumder0** [comment]
@Sanchitbajaj02 please assign this issue to me.

**Comment by anirbanmajumder0** [comment]
yes i am in SWOC
