### ISSUE TITLE
Bug: help center navbar redirection to private routes

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#206]
### What happened?

Please find below the screenshot of navbar currently used in Help Center page but the problem is that it has a logout button, home button and account button. It is good when the user is logged in but if the user is not logged in, these buttons are not required.

The proposed fix of this issue is to:
- extract the navbar code from home page and make a separate navbar component
- use `accountId` cookie to check whether the user is logged in
- based on the cookie, switch between private navbar and public navbar

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/23017ae1-c34a-47b1-b28a-71ede643fc2d)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by anirbanmajumder0** [comment]
Please assign this issue to me.

**Comment by Sanchitbajaj02** [comment]
@anirbanmajumder0 assign this issue to you.

**Comment by Sanchitbajaj02** [comment]
@anirbanmajumder0 under which event are you registered? SWOC or IWOC?

**Comment by anirbanmajumder0** [comment]
Swoc

**Comment by anirbanmajumder0** [comment]
Swoc
