### ISSUE TITLE
Feat: Add post section

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#21]
### What feature?

Create the add post section where users can add the post on the feed section.
The inputs will be
- text
- image
- color palette

Give this option before filling in and saving the data. 

### post section when not active on the feed page
![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/9dab67bd-d3ce-4633-b50f-6a246b82651a)

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/caad09ca-c48b-4374-8670-93654d7c90d2)

### When user wants to post
![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/c7276c18-425d-4bd5-909f-dbeef8368e89)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by kunalthedev** [comment]
I'll Do it
