### ISSUE TITLE
Bug: introduced because of pull request #199

### ISSUE THREAD

**Issue by Girishbari** [Sanchitbajaj02/palettegram#212]
### What happened?

I confirmed changes locally before pushing however still there is some problem with CSS and a bug in which anybody can delete anyone's posts
Also few console remained were not removed

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/07acaea3-7a9b-4c2e-bb0f-1a17ee003a19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
@Girishbari If you click on the content of the post, it will open to the new page with detailed information of the post with comments. You can take up this issue so that user page will open when clicked on profile name, username or photo else it will open `/post/postId`

**Comment by Girishbari** [comment]
sure

**Comment by Girishbari** [comment]
I guess this issue should be closed now

**Comment by Girishbari** [comment]
@Sanchitbajaj02  this issue was sorted ..?

**Comment by Sanchitbajaj02** [comment]
@Girishbari what was the fix?

**Comment by Sanchitbajaj02** [comment]
@Girishbari thanks for mentioning, closing this issue
