### ISSUE TITLE
Style: Back button on single post page

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#215]
### What's the suggested design idea?

Currently there is not back button for user to go back to feed page. A back button help them to continue browsing to the feed. 

> [!TIP]
> Contributor can refer the `/user/userId` or `/user/bookmark` pages

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/66d62810-5933-4de6-81e3-704eaebd3963)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by jaymehta002** [comment]
assign me this issue

**Comment by Sanchitbajaj02** [comment]
Hi @jaymehta002, assigned to you
