### ISSUE TITLE
refactor: remove redundant code of Button component

### ISSUE THREAD

**Issue by Girishbari** [Sanchitbajaj02/palettegram#218]
Currently, I saw at many instance people have created buttons with new styles for ex:-
this is the code of `components/pages/auth/login`
![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/04909e74-b710-465a-b416-0632b58e6f25)

Of course, the above code is not bad but we already have particular code for the button so can we remove such above code snippets and use the existing core component which is specifically made for the button in `components/core/button` it takes the below props
![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/88814c26-3ce1-4738-8cf6-68e0d086aa49)

Also Check the behavior of button (generally they have similar) and add the necessary code and types in `components/core/button`

**Comment by Sanchitbajaj02** [comment]
@Girishbari please finish your other issues to get assigned

**Comment by kamalsritha** [comment]
@Sanchitbajaj02 can you please assign me this issue under SWOC S4

**Comment by Sanchitbajaj02** [comment]
@kamalsritha asssigned to you

**Comment by Manishak798** [comment]
@kamalsritha any updates you have for the work you have done?

**Comment by Sanchitbajaj02** [comment]
@kamalsritha if you don't update within 24 hrs, I am unassigning the issue

**Comment by Girishbari** [comment]
assign me

**Comment by Girishbari** [comment]
close this issue, I have reviewed the codebase and there is not much requirement to change the existing buttons
