### ISSUE TITLE
make the navbar translucent

### ISSUE THREAD

**Issue by rajpootjyoti700** [Sanchitbajaj02/palettegram#221]
### What's the suggested design idea?

I made the navbar translucent by giving it a glossy glass pane effect along with little border shadow at the bottom
and also the logo in navbar have to left most corner nd content of navbar arrrangment also

### Add screenshots

![nav2](https://github.com/Sanchitbajaj02/palettegram/assets/133164017/4c658912-e4b0-4607-85e6-ab8c7a216a5b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by rajpootjyoti700** [comment]
plz assign this issue to me i want to work on it

**Comment by Manishak798** [comment]
I don't think it will go with the theme of the website.

> plz assign this issue to me i want to work on it

**Comment by Sanchitbajaj02** [comment]
Hi @rajpootjyoti700 
> I made the navbar translucent by giving it a glossy glass pane effect

This design is already implemented in the private navbar.

> also the logo in navbar have to left most corner and content of navbar arrrangment also

Can you share this design here or on discord? looks interesting but please share the design first.

**Comment by Sanchitbajaj02** [comment]
This issue has been resolved
