### ISSUE TITLE
Style: Merge Post UI

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#227]
### What's the suggested design idea?

Currently there are 2 UIs are developed into the system and both of them are being used. This issue is been raised to merge them and utilize only single post component among the application

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/47a3a93e-c1f7-4186-9979-11c035a68bd9)

In the referred screenshot,

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Girishbari** [comment]
let me do this

**Comment by Sanchitbajaj02** [comment]
@Girishbari sure, assigned to you. Few things to implement in this:

- show the delete option only on `/user/:userId`
- after clicking on delete icon, an option will appear which asks for yes or no. Use the javascript, no need to implement any library

**Comment by Girishbari** [comment]
okay

**Comment by Girishbari** [comment]
hi, I was unable to push, will do it today or tomorrow
