### ISSUE TITLE
Style: conversion of 3 column design to 2 column design

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#229]
### What's the suggested design idea?

The feed page is currently having 3 columns. The left most column only contains a user button and a bookmark button. I was thinking we could navigate those button at the top in the navbar and extend the feed panel to make a consistent 3 column structure with 75-25 ratio of main and side column.

### Removal of mention buttons

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/b3602e37-be71-48bd-b675-ef1806ddb455)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Girishbari** [comment]
assign me

**Comment by Sanchitbajaj02** [comment]
Assigned

**Comment by Girishbari** [comment]
how is it 
![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/b31c8ed6-8f96-4f99-9a3d-08fce69c1d1a)

**Comment by Girishbari** [comment]
also do you want bookmark should also need to sync with feed like profile section is..?

current bookmark 
![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/d82f318e-faf3-4c64-8551-20504d923867)

**Comment by Sanchitbajaj02** [comment]
> how is it ![image](https://private-user-images.githubusercontent.com/38005544/312935284-b31c8ed6-8f96-4f99-9a3d-08fce69c1d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDQ5MTUsIm5iZiI6MTcxMDQ0NDYxNSwicGF0aCI6Ii8zODAwNTU0NC8zMTI5MzUyODQtYjMxYzhlZDYtOGY5Ni00Zjk5LTlhM2QtMDhmY2U2OWMxZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE5MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiMjExMzNjOTFkNmE5ZTFmZjA1NGUyYTBkYjc4YzNhZWEyYzMwZWQ2YWMxZGNjNjFhNWE0YzkyYjM5NjRlMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bv8PFd8M6N1jnJ3oYjTF9bBuOMlAvYnqGgpN7_BmiPI)

It's great and is the expected result

**Comment by Sanchitbajaj02** [comment]
> also do you want bookmark should also need to sync with feed like profile section is..?
> 
> current bookmark ![image](https://private-user-images.githubusercontent.com/38005544/312936848-d82f318e-faf3-4c64-8551-20504d923867.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDQ5MTUsIm5iZiI6MTcxMDQ0NDYxNSwicGF0aCI6Ii8zODAwNTU0NC8zMTI5MzY4NDgtZDgyZjMxOGUtZmFmMy00YzY0LTg1NTEtMjA1MDRkOTIzODY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE5MzAxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2OWVmZjE2ZDFkMGNmYTdmNWZjYWNjNmJlMDgyMWFjZmIxYTJmNTc5YjFhZmQ0MGZiZDI5ZTkzYjViMWMyZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vRTar2DeMhkDz-UISK9s2iPngJLCimLQdErH0fE1mB8)

Currently not have a plan for this
