### ISSUE TITLE
Bug:(Critical)  accountId is undefined

### ISSUE THREAD

**Issue by Girishbari** [Sanchitbajaj02/palettegram#235]
### What happened?

This bug is introduced in or after #230 **commit** where if one visits his/her profile the accountId (which is user's Id)  is **undefined** for (more detail view below screenshots), now this is undefined because the cookies itself becomes undefined after user login's with correct email/password  or registers

## **this is just a moment after user's login**
![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/2d75e96d-792a-4fb1-a5c5-d3622e53bf5f)

## but then suddenly things go undefined
![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/ce33af06-649c-4649-abe1-e7dff4fbeb10)

## also here
![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/2d15313c-0a97-4e68-9eee-7001ac703afd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Issue is replicating again on the production server

**Comment by IrfanshaikH-7** [comment]
is this bug still there!
if yes I'll take it

**Comment by Sanchitbajaj02** [comment]
> is this bug still there! if yes I'll take it

Production isn't properly synced with issue #241 for now. Please check tomorrow whether you get the same result

**Comment by Girishbari** [comment]
this should be gone if #241 is properly merged, this can also be closed once @IrfanshaikH-7  changes is merged

**Comment by IrfanshaikH-7** [comment]
> this should be gone if #241 is properly merged, this can also be closed once @IrfanshaikH-7  changes is merged

My changes are already merged tho!

**Comment by Sanchitbajaj02** [comment]
The issue has been fixed and move to production
