### ISSUE TITLE
Bug: Fixed footer

### ISSUE THREAD

**Issue by kom-senapati** [Sanchitbajaj02/palettegram#237]
### What happened?

The footer is positioned as fixed and overlaps with the card content. The submit button lacks clear visibility and the overall appearance feels unsatisfactory.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/92045934/14d40a82-de53-4a76-be52-3d86af7a596f)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
@kom-senapati assigned to you

**Comment by Sanchitbajaj02** [comment]
@kom-senapati please implement the changes of footer in other pages as well. mentioned the same on PR
