### ISSUE TITLE
Feat: Toast library update

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#238]
### What feature?

Currently we are using react-toastify for showing the toasts. This issue is created to replace that library with https://sonner.emilkowal.ski/

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Girishbari** [comment]
assign me

**Comment by Sanchitbajaj02** [comment]
@Girishbari assigned to you. Make sure to use these properties:

- richColor property should be implemented
- expand should be true
- position should be top right

**Comment by Girishbari** [comment]
BTW its really nice Lib, how did you find it

**Comment by Sanchitbajaj02** [comment]
> BTW its really nice Lib, how did you find it

Just got to know it from some open source developers

**Comment by Girishbari** [comment]
should I change styling or let it be how it is

**Comment by Sanchitbajaj02** [comment]
> should I change styling or let it be how it is

What styling, can you explain a little bit?

**Comment by Girishbari** [comment]
[https://sonner.emilkowal.ski/styling](url)

I saw we could apply custom styles here, that's why I thought but light version of toast is also matching with theme, I guess

**Comment by Sanchitbajaj02** [comment]
> [https://sonner.emilkowal.ski/styling](url)
> 
> I saw we could apply custom styles here, that's why I thought but light version of toast is also matching with theme, I guess

I didn't know about this. I think for now, the default UI is already great so you can use that

**Comment by Girishbari** [comment]
oh ok..
