### ISSUE TITLE
Bug: Performance issues (debug with admin)

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#241]
### What happened?

Right now due to many rapid changes into the codebase has caused issues. An end to end testing is required to streamline the workflow and to proceed further for adding new features.

The interested contributor has to contact me and together we will debug the entire flow.

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by IrfanshaikH-7** [comment]
**I'm interested! count me in ..**

**Comment by Sanchitbajaj02** [comment]
> **I'm interested! count me in ..**

You're in

**Comment by utkarsh4321** [comment]
@Sanchitbajaj02 what is the issue? Here?

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 what is the issue? Here?

The process is not end to end optimised. Everytime, a new feature is added, some old features breaks. So the aim of this issue is to fix all the state and data level issues
