### ISSUE TITLE
Bug: tailwind scrollbar property disabled

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#245]
### What happened?

The project is using tailwind scrollbar property for customizing the scrollbar but currently the scrollbar is reverted back to normal due to rapid changes from other contributors.

To fix this issue:
- check for the previous PR which might overlap the property
- re-install and setup the tailwind scrollbar

> [!TIP]
> Take help from other contributors, mentors and project admin

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/f71a40e8-b55f-4461-acc4-e484a9dfc796)

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Girishbari** [comment]
assign me

**Comment by Sanchitbajaj02** [comment]
Assigned the issue to you
