### ISSUE TITLE
Feat: Implement automated reviewer assignment workflow for Pull Requests 

### ISSUE THREAD

**Issue by harmeetsingh11** [Sanchitbajaj02/palettegram#249]
### What feature?

This issue addresses the need for a GitHub Actions workflow that automatically assigns reviewers to pull requests upon their opening. Automating the reviewer assignment process will streamline code review processes and ensure timely feedback from team members.

### Proposed Feature:
The proposed feature involves the creation of a GitHub Actions workflow that triggers upon the opening of a pull request. This workflow will automatically assign designated reviewers based on predefined list of reviewers in the workflow config.

### Expected Behavior:
- When a pull request is opened, the workflow should trigger automatically.
- Based on defined rules or configurations, reviewers will be assigned to the pull request.
- Reviewer assignments should be customizable and adaptable to project-specific requirements.

### Benefits:
- Streamlines the code review process by automating reviewer assignments.
- Ensures timely feedback and reduces bottlenecks in the development workflow.
- Improves collaboration and accountability among team members.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue
- [X] I am SWOC'2024 contributor

**Comment by Sanchitbajaj02** [comment]
Hi @harmeetsingh11 this feature is already implemented. When user creates a pull request, contributor will automatically assigned

**Comment by harmeetsingh11** [comment]
@Sanchitbajaj02 when someone creates a pull request, a reviewer/reviewrers will be automatically assigned not contributor.

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 when someone creates a pull request, a reviewer/reviewrers will be automatically assigned not contributor.

But there is only one reviewer for now, how is it giving benefit to the project?
