### ISSUE TITLE
Style: Responsive Dark-Light Mode Icon Position Adjustment

### ISSUE THREAD

**Issue by Bittukr7479** [Sanchitbajaj02/palettegram#253]
### What's the suggested design idea?

Currently, the dark-light mode icon's position in responsive mode doesn't align well with our design principles or user expectations. This issue aims to adjust its placement for better visibility and accessibility across various screen sizes.

### Add screenshots

Before change:
![Screenshot 2024-02-19 022523](https://github.com/Sanchitbajaj02/palettegram/assets/123286618/02ae2b56-36b9-40f5-a002-07baf9332ae5)

After change:
![Screenshot 2024-02-19 022430](https://github.com/Sanchitbajaj02/palettegram/assets/123286618/3fc9d6a3-b705-49c3-871b-b3fbbd4f6abc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Bittukr7479** [comment]
Hello @Sanchitbajaj02,  please assign me this task under swoc'24.

**Comment by Sanchitbajaj02** [comment]
> Hello @Sanchitbajaj02,  please assign me this task under swoc'24.

Sure, assigned to you

**Comment by Bittukr7479** [comment]
Hello @Sanchitbajaj02, please accept my pull request.

**Comment by Sanchitbajaj02** [comment]
> Hello @Sanchitbajaj02, please merge my pull request.

Requested the changes. Please fix them. All follow the pull request name guidelines

**Comment by Bittukr7479** [comment]
@Sanchitbajaj02 please check it.
