### ISSUE TITLE
Bug: Fix footer overlapping bug 

### ISSUE THREAD

**Issue by IrfanshaikH-7** [Sanchitbajaj02/palettegram#261]
### What happened?

Footer is overlapping with other components when scrolling to end of footer.

### Add screenshots

[
![Screenshot 2024-02-25 135930](https://github.com/Sanchitbajaj02/palettegram/assets/124655192/5813328f-e6db-4380-9504-be30946a6185)
](url)

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
@IrfanshaikH-7 assigned to you
