### ISSUE TITLE
Bug: Navbar not visible properly in Mobile Version.

### ISSUE THREAD

**Issue by NilanchalaPanda** [Sanchitbajaj02/palettegram#277]
### What happened?

When the website is viewed on Mobile version, the navbar is overlapping with other content of the website like hero section and other similar sections. Also the content like "Register & Login" are not visible in mobile version.

Would love to contribute on this issue and work upon to resolve the issue as a GSSoC'24 Contributor. Looking forward to you response and to work with Palettegram.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/110488337/6f7da47f-5168-4a34-81bd-5ce607d9a795)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @NilanchalaPanda 

> the navbar is overlapping with other content of the website like hero section and other similar sections

What are your suggestions to improve that?

**Comment by NilanchalaPanda** [comment]
We can make the background solid and also increase the width a bit to make it look more appealing. After that, we can add the links to it like `Register` and `Login` which are visible in desktop view, but hidden in mobile view.

**Comment by NilanchalaPanda** [comment]
Hey @Sanchitbajaj02, can you add the appropriate labels to the issue like GSSoC'24 and levels so that my contribution is considered by the GSSoC team. Looking forward to your response 🙌🏻

**Comment by NilanchalaPanda** [comment]
Hey @Sanchitbajaj02, hope you doing well. Can you add proper labels to the issue, so that I can raise PR to get it reviewed. Looking forward to your response.

**Comment by Sanchitbajaj02** [comment]
> Hey @Sanchitbajaj02, hope you doing well. Can you add proper labels to the issue, so that I can raise PR to get it reviewed. Looking forward to your response.

Sorry for the late reply, tags have been added

**Comment by NilanchalaPanda** [comment]
No worries @Sanchitbajaj02, thanks for the update. Will raise a PR by today.

**Comment by Sanchitbajaj02** [comment]
> No worries @Sanchitbajaj02, thanks for the update. Will raise a PR by today.

Since I didn't get your reply, so I am unassigning this issue

**Comment by NilanchalaPanda** [comment]
I was out of station because of some urgent family work. Have completed the issue, just about to raise PR today. You can review it once here only.

![PALETTEGRAM](https://github.com/Sanchitbajaj02/palettegram/assets/110488337/054fab5a-7126-4f2e-92e9-df3582418271)

**Comment by NilanchalaPanda** [comment]
Apologies for the delay, you can again assign it, will raise the PR rn.

**Comment by Sanchitbajaj02** [comment]
> I was out of station because of some urgent family work
You should have said that in the issue.

The design looks good, please make a PR accordingly

**Comment by NilanchalaPanda** [comment]
> > I was out of station because of some urgent family work
> > You should have said that in the issue.
> 
> The design looks good, please make a PR accordingly

Yes.

**Comment by hvmanker** [comment]
why is this issue openned still ?
