### ISSUE TITLE
Feat: add a gallery dashboard to show the features 

### ISSUE THREAD

**Issue by kairveeehh** [Sanchitbajaj02/palettegram#285]
### What feature?
@Sanchitbajaj02 
the home page lacks details about what the website offers , so creating a dashboard gallery will be useful 
### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
> the home page lacks details about what the website offers , so creating a dashboard gallery will be useful

What are you planning to add in the gallery section?

**Comment by harini-1597** [comment]
Hey @Sanchitbajaj02
I feel that the website home page doesn't really tell much about what the website is for and only asks you to sign in leading to lesser user retention;
I would like the home-page scroll to offer some more information as user scrolls down:
-> What is Palettegram?
-> Who is Palettegram for? (already exists)
-> Why Palettegram?
(and some other useful info...)


Could you assign this to me too as a GSSoC contributor?

**Comment by Sanchitbajaj02** [comment]
@harini-1597 assigned the issue to you

**Comment by harini-1597** [comment]
Hey @Sanchitbajaj02!
This is what I've done:

https://github.com/Sanchitbajaj02/palettegram/assets/128628820/a9835717-40fa-4101-8d8c-8773c505f719

**Do let me know what you think!**

Anything else to add / some features you'd like to add, etc

**Comment by Sanchitbajaj02** [comment]
Hey @harini-1597 the design looks great 🤩

Just a small pointer, try changing the color of illustrations to the one we are using in the theme. Also, do check the responsivity of this page

**Comment by harini-1597** [comment]
Hey
I tried searching for b/w images like the ones being used and couldn't find any good ones😔.. plus re-coloring the existing ones made the page look very dull.
So I instead changed the header image color. Do tell what you think of it, if it's good or you'd like to change it


https://github.com/Sanchitbajaj02/palettegram/assets/128628820/ef29b10b-2033-426f-a888-d73a718fa08f

**Comment by Sanchitbajaj02** [comment]
> I tried searching for b/w images like the ones being used and couldn't find any good ones😔.. plus re-coloring the existing ones made the page look very dull.

No, not recolor the first one. I am saying that the one you have added after the first section, try to add the pink shade that we are using to implement. What you can do is find the **SVG** ones for the same and implement CSS in them. If there is any problem, please let me know

**Comment by harini-1597** [comment]
What about this? The image is recolored using the exact pink of the website?
![Screen Shot 2024-05-16 at 12 07 11 PM](https://github.com/Sanchitbajaj02/palettegram/assets/128628820/116886ec-82e3-463b-b72b-0172ffd4e3bc)

**Difference in old / new:**
![Screen Shot 2024-05-16 at 12 08 56 PM](https://github.com/Sanchitbajaj02/palettegram/assets/128628820/80447ad6-03bd-4276-a318-13a6e2fbb044)

**Comment by Sanchitbajaj02** [comment]
Yeah, that looks good, raise a PR

**Comment by Sanchitbajaj02** [comment]
## Re-opening the issue for minor bug:

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/7b515ae9-dd09-46ef-b25d-b4fa0a8a380e)

As you can see in the above screenshot, the images are partially loading. Also include the images which are without white spaces

**Comment by harini-1597** [comment]
@Sanchitbajaj02 A little help- Do I create a new PR for the new changes as that one is Merged? Could you help me as to how to sync the newer changes?
