### ISSUE TITLE
Docs: Adding GSSoC '24 to the 'Featured In' section of documentation

### ISSUE THREAD

**Issue by SpaciousCoder78** [Sanchitbajaj02/palettegram#290]
### What you want to add in the documentation?

This project has been listed in GSSoC '24. However the documentation has not been updated for the same. 

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/88923986/8564ecd0-4a41-432c-82a4-18ac705e3ec9)
GSSoC '24 needs to be added to this section

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by SpaciousCoder78** [comment]
I would like to work on this issue. Please assign it to me under GSSoC '24

**Comment by Sanchitbajaj02** [comment]
Assign to you

**Comment by rajbhoyar729** [comment]
hello can i work on it

**Comment by SpaciousCoder78** [comment]
> hello can i work on it

I'm already working on it mate
