### ISSUE TITLE
Bug: Character Limit Bug in Text Editor

### ISSUE THREAD

**Issue by RashidSiddiqui2004** [Sanchitbajaj02/palettegram#292]
###  Character Limit Bug in Text Editor

_**Users**_ are able to **_exceed the character capacity limit in the text editor._** Instead of restricting _users from writing more text_ when they exceed the limit, the character limit goes negative, causing unexpected behavior. This bug hinders the functionality of the text editor and can lead to _data inconsistencies._

###  Navbar Backdrop Blur Issue
The _navbar in the project_ currently has the backdrop-blur-sm property applied, intending to blur the background elements. However, the blur effect is not applied correctly, as the **background elements are still visible through the navbar.** This issue affects the visual aesthetics and intended design of the navbar.

### Add screenshots

**_Character Limit Bug in Text Editor_**

![issu3](https://github.com/Sanchitbajaj02/palettegram/assets/124426004/59851ee0-6621-4265-a54d-54b6d681d1ff)

 **_Navbar Backdrop Blur Issue_**

![issue4](https://github.com/Sanchitbajaj02/palettegram/assets/124426004/14bec95f-36a3-42d4-a1e4-6716fe08ee44)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by RashidSiddiqui2004** [comment]
@Sanchitbajaj02 Please assign this task to me under GSSOC'24. 😊✨

**Comment by Sanchitbajaj02** [comment]
Hi @RashidSiddiqui2004 Thanks for raising issue. Assiging it to you

>Navbar Backdrop Blur Issue

I recommend you to create the issue for this bug separately. Thanks

**Comment by RashidSiddiqui2004** [comment]
@Sanchitbajaj02 ok sir 😊✨
