### ISSUE TITLE
Integrating Google Sign-In

### ISSUE THREAD

**Issue by noureennaaz** [Sanchitbajaj02/palettegram#293]
### What feature?

Adding the Sign-in with google will make the login and sign-up process easier. It will help user to create secure and passwordless account. Users can sign-in once to a Google account and then sign in automatically or with one click on other sites.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Functionality is partially implemented. Just have to fix on the server end to enable it. Also this issue is duplicate so closing that
Refer: #284
