### ISSUE TITLE
Feat:Newsletter section for engaging with users and collecting their emails

### ISSUE THREAD

**Issue by Adeesh-bode** [Sanchitbajaj02/palettegram#295]
### What feature?

The issue involves creating a newsletter section on a website or application to engage with users and collect their email addresses. This feature aims to facilitate communication with users, keep them informed about updates or promotions, and potentially increase user retention and interaction. The implementation would typically include designing the user interface for the newsletter signup, integrating it with the backend systems, and ensuring compliance with data protection regulations.

### Add screenshots

will generate a pr and add screenshot there on development

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Adeesh-bode assigned the issue to you

**Comment by Sanchitbajaj02** [comment]
@Adeesh-bode since, I didn't hear anything from you, so unassigning this issue

**Comment by Adeesh-bode** [comment]
brother ,  I was on vacation from 13th may to 22th may to manali , Now I am working on issue which I have assigned

**Comment by Adeesh-bode** [comment]
I have done frontend for newletter , since I dont know about appwrite , I will learn it by refering other part of projects of yours

**Comment by Sanchitbajaj02** [comment]
> brother , I was on vacation from 13th may to 22th may to manali , Now I am working on issue which I have assigned

You should have just write this message on 13th, btw how was your vacation?

**Comment by Adeesh-bode** [comment]
great , himachal is a beauty!

**Comment by Sanchitbajaj02** [comment]
@Adeesh-bode Please do the changes that are suggested in your PR to get it merged. Otherwise, I will close the PR and unassign you to this issue
