### ISSUE TITLE
Bug: when you use on mobile , you can't see the login register button if you haven't  logged in.

### ISSUE THREAD

**Issue by Adeesh-bode** [Sanchitbajaj02/palettegram#296]
### What happened?

a bug affecting mobile users where the login and register buttons are not visible to users who are not already logged in. This bug impacts user accessibility and functionality of the website or application on mobile devices, potentially preventing new users from registering or existing users from logging in. The task would involve diagnosing and fixing the UI/UX issues to ensure that these essential buttons are visible and accessible on all mobile devices.

### Add screenshots

With pr , on development

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Adeesh-bode the bug has already been raised so this is duplicate.
