### ISSUE TITLE
Bug: Dockerfile size is too large

### ISSUE THREAD

**Issue by Bhavya-55** [Sanchitbajaj02/palettegram#297]
### What happened?

Dockerfile size needs to be reduced as it will also reduce build time helps in optimisation

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Bhavya-55** [comment]
@Sanchitbajaj02  I can work on this I have already worked on this pls assign to me

**Comment by Sanchitbajaj02** [comment]
Hi @Bhavya-55 
Docker functionality is down right now in this application. While controlling the docker size there is a scope of improving the docker dependencies. Please also look into that

**Comment by aryasoni98** [comment]
I would like to work on it

**Comment by Sanchitbajaj02** [comment]
> I would like to work on it

PR already been raised in review process. If it gets closed or rejected, then only you can work on that
