### ISSUE TITLE
Bug: Navbar Backdrop Blur Issue 

### ISSUE THREAD

**Issue by RashidSiddiqui2004** [Sanchitbajaj02/palettegram#298]
### What happened?

The **_navbar_** in the project currently has the _backdrop-blur-sm property_ applied, intending to blur the background elements. However, the blur effect is not applied correctly, as the **_background elements are still visible through the navbar_**. This issue affects the _visual aesthetics and intended design of the navbar_.

### Add screenshots

Navbar Backdrop Blur Issue
 
![issue4](https://github.com/Sanchitbajaj02/palettegram/assets/124426004/bc03ec0d-6a8d-4478-a07f-11da278df64b)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Assigned this issue to you

**Comment by Amitooo1** [comment]
Nice bug, can i also try @Sanchitbajaj02 ?
