### ISSUE TITLE
Feat: Adding Social media icons in footer section 

### ISSUE THREAD

**Issue by SalehaTabassum** [Sanchitbajaj02/palettegram#303]
### What feature?

I would like to add social media icons in the footer section and add hover effects to them 
Please assign this issue to me under GSSOC 2024 and add necessary labels for it 
@s

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @SalehaTabassum 
What social media icons are you planning to add? Because I didn't create any social media related to palettegram

**Comment by SalehaTabassum** [comment]
> Hi @SalehaTabassum What social media icons are you planning to add? Because I didn't create any social media related to palettegram

Social media icons like GitHub ,Facebook,Twitter and whatever if you wish to add

**Comment by Sanchitbajaj02** [comment]
> > Hi @SalehaTabassum What social media icons are you planning to add? Because I didn't create any social media related to palettegram
> 
> Social media icons like GitHub ,Facebook,Twitter and whatever if you wish to add

Not planning to organize Social Media right now since the community isn't that big 😊. Closing this issue for now
