### ISSUE TITLE
Bug: Navbar toggler not working in mobile device

### ISSUE THREAD

**Issue by AbhiDiva96** [Sanchitbajaj02/palettegram#305]
### What happened?

navbar right side toggler/sidebar is not working properly on the mobile device and the theme(dark/light) should be on the right-most corner.

@Sanchitbajaj02 

Please assigned me under the GSSoC'24

### Add screenshots

In window

![Screenshot 2024-05-13 203728](https://github.com/Sanchitbajaj02/palettegram/assets/112077897/b8508bc0-8001-49a4-a8b9-cb0ef99a134f)

In mobile

![Screenshot 2024-05-13 203717](https://github.com/Sanchitbajaj02/palettegram/assets/112077897/0fe262ca-4c4e-4f53-8dd5-511887bf326c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by AbhiDiva96** [comment]
Thanks for assigning, soon I will be back with PR.

**Comment by Amitooo1** [comment]
@Sanchitbajaj02 i would also like to work on this, can you assign me if there will be no PR in 24hrs?

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 i would also like to work on this, can you assign me if there will be no PR in 24hrs?

I will assign you if I didn't get response in 36 hrs

**Comment by AbhiDiva96** [comment]
Hey dear @Amitooo1 
I am working on this issue please find another one.
