### ISSUE TITLE
Bug: Not able to login with registor form Oauth 

### ISSUE THREAD

**Issue by ArtiGaund** [Sanchitbajaj02/palettegram#307]
### What happened?

![Screenshot (282)](https://github.com/Sanchitbajaj02/palettegram/assets/38074085/fcf1e8c7-5dc9-4c38-815e-be452b4cd0dc)
when I am trying to login through oAuth authentication, I am getting this error

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by ArtiGaund** [comment]
For configuration, I have make account on appwrite and have to do add in the code?

**Comment by Sanchitbajaj02** [comment]
> For configuration, I have to make an account on AppWrite and add in the code. Can I do it?

Yes, you can do that. Just follow the official docs of Appwrite to configure

**Comment by ArtiGaund** [comment]
Can you assign it to me?

**Comment by Sanchitbajaj02** [comment]
> Can you assign it to me?

What is your proposal for the improvement of this issue? Because the configuration is pending from my side. I didn't enabled that because of some business logic issues

**Comment by ArtiGaund** [comment]
![Screenshot (298)](https://github.com/Sanchitbajaj02/palettegram/assets/38074085/0d8d8525-603a-4d81-92c1-59c0f5de3c10)
![Screenshot (299)](https://github.com/Sanchitbajaj02/palettegram/assets/38074085/b96637c9-a311-4eb5-9b64-1704fcc1e332)
Before it was done like this, registering the project in Github developer settings will provide the App ID and App secret, You can add that to appwrite project in OAuth and fill out the form, and it will then enable the configuration. Then you can code for github OAuth configuration as given in the doc.

**Comment by Sanchitbajaj02** [comment]
I know how to add that😅,
The business logic around this not correct. Like when user signs up with services like github or google, their authentication is done but they didn't get the privileges to perform any action due to db checks

**Comment by ArtiGaund** [comment]
I used Appwrite last year in one of my project, but I haven't done OAuth because I was able to verify the account of user through email verification link, Because AppWrite needs verified user to perform any action, it don't allow guest account to perform CRUD operation. But I will try to do OAuth on that previous project of mine.

**Comment by Sanchitbajaj02** [comment]
_For future visitors_

## The issue is not a bug or anything, it is just that the business is not properly setup with External OAuth
