### ISSUE TITLE
Bug: Landimg page not responsive at md screen

### ISSUE THREAD

**Issue by SnehansuBehera** [Sanchitbajaj02/palettegram#311]
### What happened?

The UI of the landing page distorted at the screen sizes exceeding 768px - not proper alignment of the containers needs spacing i.e margin and padding at both axis.

 

### Add screenshots

![Screenshot 2024-05-15 220901](https://github.com/Sanchitbajaj02/palettegram/assets/121883802/bcc93424-1b05-4be9-8c37-3b8a546f0c72)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by SnehansuBehera** [comment]
hi @Sanchitbajaj02 I am contributor at gssoc'24 and i want to contribute to the issue, please assign me the issue

**Comment by Sanchitbajaj02** [comment]
Hey @SnehansuBehera thanks for raising under gssoc'24.
Actually for the responsiveness of this page, I am using tailwind CSS responsive web design strategy. I don't want to implement customs in this project so can you suggest what we can do for the responsiveness. 

Do check Tailwind CSS official documentation and let me know what they recommend for the tab screen sizes

**Comment by SnehansuBehera** [comment]
@Sanchitbajaj02 i have gone through the codebase of the project, we will not add any custom css to the file instead we can use the Responsive feat of tailwind css and can modify the code using attributes like md: , lg: for responsiveness of the website for every screen sizes

**Comment by yashd-dev** [comment]
Hi there, I'm assigning this issue to you provided that you ensure proper alignment and spacing of every page.

**Comment by SnehansuBehera** [comment]
@yashd-dev  Please add the labels like gssoc level1 level 2 so that the gssoc team could track my pr.

**Comment by Sanchitbajaj02** [comment]
@SnehansuBehera I didn't get any positive response from your side on #324. The issue you are facing at the time of login is because by mistake you have upgraded the version of Appwrite. Re-install the appwrite package with version 13 and it will be resolved.
Please complete this PR or else it will be closed in 2 days

**Comment by SnehansuBehera** [comment]
> @SnehansuBehera I didn't get any positive response from your side on #324. The issue you are facing at the time of login is because by mistake you have upgraded the version of Appwrite. Re-install the appwrite package with version 13 and it will be resolved. Please complete this PR or else it will be closed in 2 days

I tried everything, tried with brave browser, tried with edge browser, tried with incognito but still unable to create the account or login and my Appwrite version is 13 , i checked btw i have made every page responsive even the pages linked in the footer links other than the pages beyond the "Start your journey" link. Every time i enter the credentials this pop-up comes --

![Screenshot 2024-05-29 121308](https://github.com/Sanchitbajaj02/palettegram/assets/121883802/f892618f-6785-4a33-be1a-5e971cd1a881)
 
and i want to know whether this pop is something related to this or not ---
