### ISSUE TITLE
The login with Google and Login with the Github is not working 

### ISSUE THREAD

**Issue by suraj-9849** [Sanchitbajaj02/palettegram#313]
### What feature?

I would like to work on this issue please assign this to me. Under @gssoc @Sanchitbajaj02 

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/146669517/500992a3-73ee-4903-b7bb-0c42cbd496a4)
it is taking me to the below page
![image](https://github.com/Sanchitbajaj02/palettegram/assets/146669517/8e035f3f-6319-45cf-80ca-bba50256c0d3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by yashd-dev** [comment]
Hello, Functionality is partially implemented and this issue is a duplicate so closing it.

Refer: #284
