### ISSUE TITLE
Bug: Error Registering

### ISSUE THREAD

**Issue by JuanPabloDiaz** [Sanchitbajaj02/palettegram#314]
### What happened?

I am unable to register. I am getting an error message that states that the password doesnt match but it does.

I am copping and pasting the password from my password manager.

What is the criteria for the password?

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/25883220/caafec0a-5b51-4d38-83f9-9f877a8c82a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by ArtiGaund** [comment]
Its password format doesn't match. Password fornat is mentioned below the password field, its working fine.

**Comment by JuanPabloDiaz** [comment]
Well, my password does match the requirements.

"Password must contain a character, a number and a special character"

example:

PQ0e]6I7n|sS<Mfp

**Comment by JuanPabloDiaz** [comment]
I just tried using `LL*?|"Glm-i2M1V5` and got the same error.

Please try using the same password to register

**Comment by JuanPabloDiaz** [comment]
I am using M. edge

**Comment by yashd-dev** [comment]
Hi there, there is a similar issue #300 assigned to someone else. The issue you are specifically facing is regarding the regex.

**Comment by JuanPabloDiaz** [comment]
its not the same error message. What is regex?

**Comment by yashd-dev** [comment]
I agree it's not the same error, that's why I said it's "similar". Read more about regex here [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions), explore the repository and once you get an idea of how you would fix it, comment it here and you will be assigned this issue.

**Comment by Sanchitbajaj02** [comment]
> I just tried using `LL*?|"Glm-i2M1V5` and got the same error.
> 
> Please try using the same password to register

Hi @JuanPabloDiaz 
Sorry for the late reply.

According to the configuration, The valid characters are: `a-z`, `A-Z`, `0-9`, `@` and `_`
Other than that, you can't use any character. This is because someone might add some scripting using the `<` or `>` characters or `"` character to inject into the system

**Comment by JuanPabloDiaz** [comment]
That makes sense.

In that case, I suggest adding the allowed special characters so the user is aware of what's going on.
As well as changing the error message to invalid password or something like that.

**Comment by JuanPabloDiaz** [comment]
I just cloned the repo and tried to run it and got this message so I installed dependencies and it changed the yarn.lock file and package.json file.

![image](https://github.com/Sanchitbajaj02/palettegram/assets/25883220/81ec7def-8cdc-4eda-8359-2389a304019b)

**Comment by JuanPabloDiaz** [comment]
What do you think about the new error message I just added @Sanchitbajaj02 and @yashd-dev?

`Invalid password. Allowed special characters are @, _, !, #, $, %, ^, &, *, -, +, =`

**Comment by Sanchitbajaj02** [comment]
> What do you think about the new error message I just added @Sanchitbajaj02 and @yashd-dev?
> 
> `Invalid password. Allowed special characters are @, _, !, #, $, %, ^, &, *, -, +, =`
> 
> 

I think we can exclude *, -, +, = as it might result in some mathematical issues as well as exclude single and double quotes.

**Comment by JuanPabloDiaz** [comment]
Is there a particular reason why the password is only `6-16 characters length`? 

I suggest increasing it to `8-32` characters. I believe it is a good idea as it aligns with industry standards and improves security. Longer passwords are harder to crack.

**Comment by ArtiGaund** [comment]
I am not able to login today, It showing Login failed! Please click on register to make account error. When I am resetting password,  able to do reset but i am trying to do login again its showing same error. 
![Screenshot (306)](https://github.com/Sanchitbajaj02/palettegram/assets/38074085/cb84f66c-8a17-46d8-93c4-549cca500870)

**Comment by Sanchitbajaj02** [comment]
> Is there a particular reason why the password is only `6-16 characters length`?
> 
> I suggest increasing it to `8-32` characters. I believe it is a good idea as it aligns with industry standards and improves security. Longer passwords are harder to crack.

the we can set the lower limit to be 6 and upper limit would be 24, what do you say?

**Comment by Sanchitbajaj02** [comment]
> I am not able to login today, It showing Login failed! Please click on register to make account error. When I am resetting password, able to do reset but i am trying to do login again its showing same error. ![Screenshot (306)](https://private-user-images.githubusercontent.com/38074085/331608435-cb84f66c-8a17-46d8-93c4-549cca500870.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzQyMDMsIm5iZiI6MTcxNTk3MzkwMywicGF0aCI6Ii8zODA3NDA4NS8zMzE2MDg0MzUtY2I4NGY2NmMtOGExNy00NmQ4LTkzYzQtNTQ5Y2NhNTAwODcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE3VDE5MjUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZTg5NWE3ZTYyNDRiMWNiNWJkZWNkNTVmOTJhNjg4NWEwNGFkOWU4ZjA1ODYwYWM0MjI4NmQ4ODI5Y2E2YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H7IpYFvQj2G98qUcj_LGwfVQmY31zfvFu6PB53qibRw)

have you verify your account by going on your email?

**Comment by ArtiGaund** [comment]
account was verified, yesterday i was using it, but its not working today.

**Comment by JuanPabloDiaz** [comment]
> lower limit to be 6 and upper limit would be 24, what do you say?

That's a reasonable choice. It provides a balance between user convenience and security.
