### ISSUE TITLE
Bug: Google Auth and Github Auth is not work 

### ISSUE THREAD

**Issue by GOURAVSINGH19** [Sanchitbajaj02/palettegram#315]
### What happened?

in sign page google auth and github is not working properly.
If you doesn't assign this issue before then assign me.

### Add screenshots

https://github.com/Sanchitbajaj02/palettegram/assets/120244528/92edc274-28dd-461b-b962-8c376f2238db

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by yashd-dev** [comment]
Hello, Functionality is partially implemented and this issue is a duplicate so closing it.


Refer: #284
