### ISSUE TITLE
Bug:  Hameburger doesn't working properly .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Sanchitbajaj02/palettegram#317]
### What happened?

In mobile view after clicking the hamburger menu not showing the login and signup option .

### Add screenshots

![Screenshot 2024-05-17 134847](https://github.com/Sanchitbajaj02/palettegram/assets/118350936/ce8c872e-6ace-49d4-ba71-9c4cb69956e7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by yashd-dev** [comment]
Hi there, this is a duplicate issue, kindly refer to issue #305
