### ISSUE TITLE
Bug: Mobile Responsiveness of Terms and Conditions and Privacy Policy Pages

### ISSUE THREAD

**Issue by Aniket-2504** [Sanchitbajaj02/palettegram#318]
Hello @Sanchitbajaj02 , 

This is the Issue I want to fix 

### What happened?

# Problem:

The content on the Terms and Conditions and Privacy Policy pages is not properly aligned when viewed on mobile devices.

# Proposed Solution:
### Please assign me this issue. I will work to improve the alignment and overall user experience on mobile.

Looking forward to hearing from you.

### I am attaching the screenshots for more understanding

![Screenshot 2024-05-17 143231](https://github.com/Sanchitbajaj02/palettegram/assets/145179532/6a4eb82f-ce16-42f4-bb34-d7755c5fe14c)
![Screenshot 2024-05-17 143250](https://github.com/Sanchitbajaj02/palettegram/assets/145179532/77b33dc1-be39-4315-ae2c-1be431f3cb96)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by yashd-dev** [comment]
Hi there, this is a duplicate issue so I am closing it, kindly refer to issue #311

**Comment by Aniket-2504** [comment]
ok bro no worries
