### ISSUE TITLE
Feat:  Adding HEX,HSL,RGB,RGBA in the input of the colour picker

### ISSUE THREAD

**Issue by yashd-dev** [Sanchitbajaj02/palettegram#321]
### What feature?

Currently, the colour picker in the palette maker does not have an input field for entering specific colour values. I am willing to assign this issue to someone who can provide a well-detailed comment on how they plan to implement this feature.

For the colour picker, we have used react-colourful. Please refer to the [Documentation](https://github.com/omgovich/react-colorful?tab=readme-ov-file#how-to-paste-or-type-a-color) to implement this feature.

### Add screenshots

# The color picker mentioned above

![image](https://github.com/Sanchitbajaj02/palettegram/assets/78804783/0c6febe0-ef63-4ccb-877b-7fdfcb127d7a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by harini-1597** [comment]
Hi! I'm interested in this issue; if you don't mind me asking , which specific page/file does this refer to?

**Comment by harini-1597** [comment]
Hi! I'm interested in this issue but I'm unsure of how exactly to get this component rendered locally as currently I'm only able to view the homepage, and the only available actions on that are Login / Register.
Could you help me out?

**Comment by yashd-dev** [comment]
Hey there, once you log in, you will see these components under the /feed route. Read all the docs to set up the backend of the app (Appwrite) on your local machine. [Link](https://github.com/Sanchitbajaj02/palettegram/tree/master/docs)

**Comment by harini-1597** [comment]
Hi. I am facing an issue with building the backend of this application. I set up my Appwrite Cloud and all keys etc in the env file as such:
![Screen Shot 2024-05-31 at 10 35 07 PM](https://github.com/Sanchitbajaj02/palettegram/assets/128628820/74265cf5-c57c-44b7-ac16-9d8ff2e17e45)

I just did that, ran yarn schema:prepare, which generated the schema.json file
But, when I register, it is giving me this error:
![Screen Shot 2024-05-31 at 10 37 27 PM](https://github.com/Sanchitbajaj02/palettegram/assets/128628820/1ef2d0db-e70e-401d-8120-2f9a60e59031)

The issue:

### Could you give a clear step-by-step of how I register as a new user?

As I'd like to acces the internal structure/working of the app

**Comment by Sanchitbajaj02** [comment]
@harini-1597, Please go to Appwrite cloud and check whether you are able to see the databases?

**Comment by harini-1597** [comment]
I am able to see the databases, etc. Could you just give me a step-by-step as to how to register as a new user on localhost?

**Comment by harini-1597** [comment]
Hi
I've implemented a field which allows entering hex color codes to modify the color:

https://github.com/Sanchitbajaj02/palettegram/assets/128628820/ec4ad0be-5477-4304-8a61-5a43d3ed8331

Do lmk what you think

**Comment by Sanchitbajaj02** [comment]
Please reduce the spaces between the text fields then I think it would be fine

**Comment by harini-1597** [comment]
How's this?

https://github.com/Sanchitbajaj02/palettegram/assets/128628820/ee9ba3b9-ef7a-4395-aa7a-01953634589b
