### ISSUE TITLE
Bug: in mobile view after click on hamburger 4 option only icon is showing 

### ISSUE THREAD

**Issue by kapilG0** [Sanchitbajaj02/palettegram#322]
### What happened?

I think after click on hamburger icons on the 4 option profile show also come as text only icon showing 
![Screenshot_20240518_125833](https://github.com/Sanchitbajaj02/palettegram/assets/59639410/cd8301da-2b55-4fb9-ab36-e454445e144b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @Sanchitbajaj02 please assign this issue to me under gssoc 24

**Comment by Sanchitbajaj02** [comment]
> Hello @Sanchitbajaj02 please assign this issue to me under gssoc 24

Hi @kapilG0 sorry to tell you but this issue is being addressed and PR is under review process. You can raise or solve another issue
