### ISSUE TITLE
Bug: Alignment needs to be done check your feed and profile button

### ISSUE THREAD

**Issue by kapilG0** [Sanchitbajaj02/palettegram#323]
### What happened?

![Screenshot_20240518_130113](https://github.com/Sanchitbajaj02/palettegram/assets/59639410/787ece89-6e2a-4a71-ba57-3ffae3333359)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @Sanchitbajaj02 please assign this issue to me under gssoc 24

**Comment by yashd-dev** [comment]
Hi there, this is a duplicate issue so closing it, kindly refer to issue #305
