### ISSUE TITLE
Feat: Add a Custom 404 Page

### ISSUE THREAD

**Issue by sambitsingha** [Sanchitbajaj02/palettegram#326]
### What feature?

The website needs it's own 404 page to let users know they have reached a wrong end on their side. An empty blank screen will leave users confused if the site is correctly working or not. 

### Add screenshots

![K27MW](https://github.com/Sanchitbajaj02/palettegram/assets/110420002/394eb5a5-dbd4-4e54-8f0b-f0df61b10c2c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @sambitsingha 
It already has its 404 page, have a look:

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/717e1aa8-969a-4262-9420-a9ef23d385ff)

If you're planning to enhance it, please suggest your ideas and based on that I will assign this issue to you

**Comment by sambitsingha** [comment]
@Sanchitbajaj02 Oh great. Ah then closing this issue. Wont contribute as it already exists.
