### ISSUE TITLE
Bug: Signup form is not functioning properly

### ISSUE THREAD

**Issue by AdhithiManjunath** [Sanchitbajaj02/palettegram#327]
### What happened?

Signup and login form isnt functioning , as even after you input the password according to the given conditions , it shows error. i would like to work on this and fix this .

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/130202961/02a06890-8bb9-4273-8ce4-142395d5155f)

on click of register now 
![image](https://github.com/Sanchitbajaj02/palettegram/assets/130202961/1a7b7e6d-f6fd-4968-aefc-2396684ec279)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by yashd-dev** [comment]
This issue is a duplicate, and a pull request is currently in progress to address it, so I am closing this. Kindly refer #314 

Read [this](https://github.com/Sanchitbajaj02/palettegram/issues/314#issuecomment-2116673388) comment for more clarification on your issue.
