### ISSUE TITLE
Auto Commenting when a PR is merged

### ISSUE THREAD

**Issue by suhanipaliwal** [Sanchitbajaj02/palettegram#332]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by yashd-dev** [comment]
Could you elaborate more on this issue and how exactly are you planning to implement it?

**Comment by suhanipaliwal** [comment]
I will adding a feature such that whenever a new pull request is merged, automatically a comment will be added on it. To do this, I will be adding a YAML file in the .github directory to define this workflow of auto commenting on the trigger of a pull request being merged.

**Comment by Sanchitbajaj02** [comment]
> I will adding a feature such that whenever a new pull request is merged, automatically a comment will be added on it. To do this, I will be adding a YAML file in the .github directory to define this workflow of auto commenting on the trigger of a pull request being merged.

What would be in the comment? because an AI code reviewer is configured along with a first commit that that wait for the reviewers to get through this. If you are planning to add a time based comment passing system so that it can ask for the contributors about their status then go ahead...
