### ISSUE TITLE
Readme_update required_Docs: 

### ISSUE THREAD

**Issue by Meetjain1** [Sanchitbajaj02/palettegram#333]
### What you want to add in the documentation?

Readme.md file is good currently but it can be more fascinating by adding animated emojis , fixing allignment , adding snapshots of our project and many more small updates 

@Sanchitbajaj02 assign this issue to me I will update it 
I am working under gssoc24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by yashd-dev** [comment]
I feel most of the issues you have raised are unnecessary:
- Adding more animated emojis is not needed, it will reduce professionalism.
- Elaborate more on "_fixing alignment_", Currently the alignment seems proper and is akin to many popular OSS projects
- A live link is present for the viewers to check the site out themselves, adding more snapshots seems unnecessary 

Kindly elaborate more on "_many more small updates_" so we can consider this a valid issue.

**Comment by Meetjain1** [comment]
> I feel most of the issues you have raised are unnecessary:
> 
> * Adding more animated emojis is not needed, it will reduce professionalism.
> * Elaborate more on "_fixing alignment_", Currently the alignment seems proper and is akin to many popular OSS projects
> * A live link is present for the viewers to check the site out themselves, adding more snapshots seems unnecessary
> 
> Kindly elaborate more on "_many more small updates_" so we can consider this a valid issue.

For your kind information I raised only two issues from which one is already assigned and other one is this .
and also closing this issue since you feel "unnecessary".
