### ISSUE TITLE
Missing LEARN.md_Docs: 

### ISSUE THREAD

**Issue by Meetjain1** [Sanchitbajaj02/palettegram#334]
### What you want to add in the documentation?

Learn.md file is missing in our current repository 
The learn.md file in GitHub is typically used as a resource to provide guidance, tutorials, or educational content related to a specific repository. This file can serve various purposes, such as introducing new users to the project, providing detailed instructions for using the codebase, or offering learning pathways for different topics covered by the repository.

@Sanchitbajaj02 assign this issue to me I will add it, I am working under gssoc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Meetjain1 assign this issue to you. Make sure to read previous docs since I have written most of the things
