### ISSUE TITLE
Feat:  Adding Animation

### ISSUE THREAD

**Issue by harshmishra19** [Sanchitbajaj02/palettegram#336]
### What feature?

- Your landing page already looks fantastic, but incorporating animations could make it even more captivating. With my experience in this area, I'm eager to contribute to this enhancement.
- If you could assign me this task under GSSOC24, I would be thrilled to work on it.

### Add screenshots

THIS IS AN EXAMPLE OF THE ANIMATION I WOULD LIKE TO ADD ON YOUR SITE
https://github.com/Sanchitbajaj02/palettegram/assets/115486960/ed57b14f-a929-4541-99fe-fbe34147491a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @harshmishra19 
I feel that the animation that you have mentioned is an overkill for the project. I want this application to be sleek and simple. Thanks for your suggestion. Closing this issue
