### ISSUE TITLE
Feat:  Adding Respective icons on the navbar

### ISSUE THREAD

**Issue by harshmishra19** [Sanchitbajaj02/palettegram#337]
### What feature?

- The current navbar lacks icons, which impacts its visual appeal and usability. Users might find it less engaging and intuitive to navigate through the website without visual cues provided by icons.
- I propose adding respective icons to the navbar to enhance its visual appeal and improve user navigation experience. These icons will align with the theme of the website and provide users with clear visual cues for each navigation option

### Add screenshots

EXAMPLE
![Screenshot 2024-05-11 080754](https://github.com/Sanchitbajaj02/palettegram/assets/115486960/bb64c59e-2317-4a5d-80a5-a0e5c1bc1ca5)
![Screenshot 2024-05-14 193517](https://github.com/Sanchitbajaj02/palettegram/assets/115486960/c79d90a5-ef4a-4b21-811d-48654c23d7ca)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @harshmishra19 
I want to know how your proposal enhances or add value to the project? You will be given 1 point if you can't justify it properly

**Comment by Sanchitbajaj02** [comment]
Hi @harshmishra19 please justify your proposal or I will close the issue

**Comment by Sanchitbajaj02** [comment]
Closing this issue since I couldn't get any reply
