### ISSUE TITLE
Feat: Appwrite version upgrade

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#338]
### What feature?

Currently, the application is running on Appwrite 13 which is a previous but LTS version. But after version 14 there are some new features introduced which enhanced the performance of the overall experience.
This issue is open for the contributors to upgrade the appwrite library and measure its impact on existing functionalities

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by pahuja-sahil** [comment]
@Sanchitbajaj02 I would like to know exactly what we have to do in this issue .. can u elaborate please.
thank you.

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 I would like to know exactly what we have to do in this issue .. can u elaborate please. thank you.

Sure, the issue is currently the system is using version 13 of the appwrite, but the latest version is 14.x.x. Generally, I can upgrade but issue is that in version 14 many existing functions got their names and functionalities changed.

So the goal of this issue is to identify those changes and made the changes in existing functions/methods so that the functionality don't change.

Hope you understand it well, If you need more clarity in the idea, let me know

**Comment by pahuja-sahil** [comment]
@Sanchitbajaj02 i have got a pretty good idea about the issue and i would like to work on it. kindly assign this issue to me under gssoc 24. I can't gurantee that issue will be resolved but would like to give a try if you don't mind.
thank you.

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 i have got a pretty good idea about the issue and i would like to work on it. kindly assign this issue to me under gssoc 24. I can't gurantee that issue will be resolved but would like to give a try if you don't mind. thank you.

The best way to start this issue to understand how Appwrite 14 works. You can create a dummy project and refer some of their youtube videos and blogs to understand it.

**Comment by pahuja-sahil** [comment]
@Sanchitbajaj02 I have just setup the your project and the site is actually commendable. I want to know the version i am seeing on appwrite console online is shown in the image below :

![image](https://github.com/Sanchitbajaj02/palettegram/assets/140882358/6a24827f-2d7a-4342-95c6-b5a615f72287)

you are telling to upgrade to appwrite 14 ..  i mean i kinda confused which version are we talking about?... if you dont mind kindly explain a little.
Thank you

**Comment by pahuja-sahil** [comment]
@Sanchitbajaj02 i have made some progress and you were talking about appwrite version 15 but when i added the latest version it upgraded to appwrite 15 .. see here in the image:

![image](https://github.com/Sanchitbajaj02/palettegram/assets/140882358/d5197fb6-efc7-42c1-b294-c0aff90a95c2)

I have made adjustment to the code where it was needed and it is working as it was when the appwrite version was 14 but there was a bug or call it issue before hand that is when we register a user , we are logged in the website and we login in again with same credential the site tells us to register although we are already register.
same issue is on the deployed app .... so my question is do i have to fix this ?...please ask if you don't understand what i am trying to explain.
Thank you.

**Comment by Sanchitbajaj02** [comment]
Hi @pahuja-sahil it's ok if the version is upgraded to 15. Just remove the `^` symbol so that nobody else could not upgrade by mistake.
As for the registration issue that you're explaining, I didn't faced that but the issue might be related to partial verification. You can check whether it is related to states or verification of db and auth. Also, raise a separate issue for that if you think it is a major bug

**Comment by pahuja-sahil** [comment]
hi @Sanchitbajaj02 I removed "^" symbol and i have also told my friend to check for the issue i mentioned earlier on your hosted app and i request you to do the same so that i can confirm that it was there before and if it was not then i guess i messed up and need to go through verification of db and auth. If it is there on the hosted website which is actually running on appwrite 13 that means that the bug was there before. I am still looking for the problem caused though.

**Comment by pahuja-sahil** [comment]
@Sanchitbajaj02 i just saw some one raised the same issue that we talked in the morning so you can give that issue to the person who raised it and i have  updated the code as per appwrite version 15 and it is working fine . if you agree i can issue a PR for this. 
Kindly reply when you are free.
Thank you.

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 i just saw some one raised the same issue that we talked in the morning so you can give that issue to the person who raised it and i have updated the code as per appwrite version 15 and it is working fine . I have checked each and every file related to appwrite and made the necessary changes required for the working of the site .If you agree i can issue a PR for this. Kindly reply when you are free. Thank you.

Please raise the PR as well as ping me on discord so that If I get any doubt, I will immediately contact you

**Comment by Sanchitbajaj02** [comment]
> hi @Sanchitbajaj02 I have removed "^" symbol and i have also told my friend to check for the issue i mentioned earlier on your hosted app and i request you to do the same so that i can confirm that it was there before and if it was not then i guess i messed up and need to go through verification of db and auth. If it is there on the hosted website which is actually running on appwrite 13 that means that the bug was there before. I am still looking for the problem's cause.

The issue is somewhat mentioned in #202. It occurred long ago, I don't know why it is occurring again

**Comment by pahuja-sahil** [comment]
> > hi @Sanchitbajaj02 I have removed "^" symbol and i have also told my friend to check for the issue i mentioned earlier on your hosted app and i request you to do the same so that i can confirm that it was there before and if it was not then i guess i messed up and need to go through verification of db and auth. If it is there on the hosted website which is actually running on appwrite 13 that means that the bug was there before. I am still looking for the problem's cause.
> 
> The issue is somewhat mentioned in #202. It occurred long ago, I don't know why it is occurring again

I hope this time it will solved by the person who raised it recently and one more thing i dont know how to ping you on discord can u tell me please?

**Comment by pahuja-sahil** [comment]
@Sanchitbajaj02  i will create a pr tomorrow there is something wrong on my end.

**Comment by pahuja-sahil** [comment]
@Sanchitbajaj02 i have cleared problems on my end and raised a pr.
kindly see when you are free.
thank you.

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 i have cleared problems on my end and raised a pr. kindly see when you are free. thank you.

Sure I will look into it. Note that it will take time for me to review it fully
