### ISSUE TITLE
Feat: Auto Commenting feature for PR Merged

### ISSUE THREAD

**Issue by Asymtode712** [Sanchitbajaj02/palettegram#339]
### What feature?

This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

### Add screenshots

![PR merged](https://github.com/Sanchitbajaj02/palettegram/assets/115717746/2f0020b4-0083-4517-a6fe-aadd8530a506)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Sanchitbajaj02 please assign me this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Asymtode712, 
The feature you are mentioned mentioned and assign to somebody else. Closing this issue as it is a duplicate
