### ISSUE TITLE
Feat: Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [Sanchitbajaj02/palettegram#340]
### What feature?

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Add screenshots

![Close Old Iss](https://github.com/Sanchitbajaj02/palettegram/assets/115717746/6e24b530-6bb3-4bee-a39d-66ebe8bc1333)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@Sanchitbajaj02 please assign me this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Asymtode712 
Explain me why do this project needs that? What if the issue that the action is closing is not fixed. Why would I need to close that is issue if it is unresolved?

**Comment by Asymtode712** [comment]
@Sanchitbajaj02 So basically, what this workflow does is that if the repo maintainer or the issue author has not interacted with the issue over a time span of 30 days, then the workflow will identify such issues and close it. If you want to fix any issues then you will definately interact with it in minimum 5-6 days or max to max 20-25 days but beyond that if it is uninteracted and goes untracked then we might just close it.

**Comment by Sanchitbajaj02** [comment]
If you notice clearly, issue #332 does the same job. So I think I can close this issue

**Comment by Asymtode712** [comment]
@Sanchitbajaj02 #332 is for commenting, this workflow is for closing old issues
