### ISSUE TITLE
Feat: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [Sanchitbajaj02/palettegram#341]
### What feature?

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

### Add screenshots

![Close Old PRs](https://github.com/Sanchitbajaj02/palettegram/assets/115717746/b96697cf-1e23-40ff-98a6-412461964ea4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Asymtode712 
Seems good but how can github action ensure that the PR is old??

**Comment by Asymtode712** [comment]
@Sanchitbajaj02 Similarly for PRs, if the repo maintainer or the issue author has not interacted with a PR over a time span of 15 days, then the workflow will identify such PRs and close them. If you have requested any changes and the issue author has not done the changes for a long time and if it goes untracked then we might just close it. Interaction can be anything including a comment or a commit.

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 Similarly for PRs, if the repo maintainer or the issue author has not interacted with a PR over a time span of 15 days, then the workflow will identify such PRs and close them. If you have requested any changes and the issue author has not done the changes for a long time and if it goes untracked then we might just close it. Interaction can be anything including a comment or a commit.

Looks good, please go ahead
