### ISSUE TITLE
Feat: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [Sanchitbajaj02/palettegram#342]
### What feature?

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Add screenshots

![issue closed](https://github.com/Sanchitbajaj02/palettegram/assets/115717746/edadf8ce-d14d-46ac-b916-84f2df3d55b4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Seems good, you can go ahead, assigned to you

**Comment by Sanchitbajaj02** [comment]
It feels same as #332 so closing this

**Comment by Asymtode712** [comment]
@Sanchitbajaj02 #332 is for commenting on PR , this workflow would comment on issue

**Comment by Asymtode712** [comment]
still if you don't need it its fine

**Comment by Sanchitbajaj02** [comment]
Re opening this issue after thinking its scope. It should only work when the PR got merged. Not when PR got closed or issue merged due to some issue

**Comment by Asymtode712** [comment]
> Re opening this issue after thinking its scope. It should only work when the PR got merged. Not when PR got closed or issue merged due to some issue

@Sanchitbajaj02 as you say, also please assign me
