### ISSUE TITLE
Feat: Animated Cursor and tilty effect

### ISSUE THREAD

**Issue by happyrao78** [Sanchitbajaj02/palettegram#344]
### What feature?

Add the animated cursor to improve the user experience and tilty effect wherever applicable to interact user.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @happyrao78 
What type of animated cursor are you mentioning? Can you show me some samples first?

**Comment by happyrao78** [comment]
@Sanchitbajaj02 
![Screenshot 2024-05-25 011250](https://github.com/Sanchitbajaj02/palettegram/assets/138770813/02965037-b439-495a-8022-7bdead1ef1c1)
![Screenshot 2024-05-25 011301](https://github.com/Sanchitbajaj02/palettegram/assets/138770813/dd34449d-7d64-465c-9bd4-2758710570f9)

**Comment by happyrao78** [comment]
> and what will you use for the mouse? the same design that is shown in the above picture?

Yes it's called animated cursor.

**Comment by Sanchitbajaj02** [comment]
> > and what will you use for the mouse? the same design that is shown in the above picture?
> 
> Yes it's called animated cursor.

Assigning it to you
