### ISSUE TITLE
Feat: Feature Request: Integrate web App Tour using  Shepherd

### ISSUE THREAD

**Issue by sneha-4-22** [Sanchitbajaj02/palettegram#347]
### What feature?

I would like to request the integration and customization of Shepherd.js for a guided tour on our website. The tour should be well-styled to match our existing website theme and provide a smooth, user-friendly experience.

**Integration:**

- Add Shepherd.js to the project for creating guided tours.
- Ensure the tour initializes correctly when the "Start Tour" button is clicked.

**Styling:**

-  Customize the appearance of the tour elements to align with the website's theme.
-  Smaller tour box size with reduced padding and adjusted font sizes.
-  Custom border, background, and text colors to match the site design.
-  Smooth transitions and hover effects.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @sneha-4-22, assign this to you
