### ISSUE TITLE
Style: hero section animation

### ISSUE THREAD

**Issue by Rohitha-pudu** [Sanchitbajaj02/palettegram#349]
### What's the suggested design idea?

text animation and button moving border animation

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by yashd-dev** [comment]
Please elaborate with examples on what type of animations you are going to use

**Comment by Rohitha-pudu** [comment]
Typing animation for text and moving border animation for button

**Comment by yashd-dev** [comment]
I read that in your original statement, there is no need to re-iterate. There are several typing and button animations. Are the buttons going to translate to the x-axis? are they going to tilt on y axis? You get the point of where I am going with this. Answer with specificity. Cite a few links or show by video.

**Comment by yashd-dev** [comment]
Also, I feel the homepage already has enough animations, too many of them won't really look good, what say @Sanchitbajaj02 ?
