### ISSUE TITLE
Bug: Unable to re-login after email verification

### ISSUE THREAD

**Issue by vinayak-vohra** [Sanchitbajaj02/palettegram#353]
### What happened?

**Steps to reproduce the bug:**
- Register via email and password
- Proceed with the email verification link received.
- User is logged in successfully. Now log out
- After logging out, the user can neither login nor register using the previous email.

### Add screenshots

**Login:**
![image](https://github.com/Sanchitbajaj02/palettegram/assets/80148777/f4a1f215-97ee-423e-b48a-eb2a47fa0437)

**Register:**
![image](https://github.com/Sanchitbajaj02/palettegram/assets/80148777/d658d628-740a-4b3d-a4bd-a54650366428)

**Video:**
https://www.loom.com/share/4eff9e07de9e4f7eb9593eecf6bbf265

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @vinayak-vohra, 
If you look into the console while authenticating, you will find the same issue as #202. Please identify the conclusion of this bug

**Comment by vinayak-vohra** [comment]
@Aamir-Manzoor I am currently working on this issue.

**Comment by Aamir-Manzoor** [comment]
okiee bro
