### ISSUE TITLE
Bug: Start tour popups are misaligned

### ISSUE THREAD

**Issue by Amitooo1** [Sanchitbajaj02/palettegram#357]
### What happened?

when we start tour to the website some of the popups are not pointing to the correct location.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/108569153/56312c73-88d3-4d6b-8eb2-680b7cbf9ae3)

![image](https://github.com/Sanchitbajaj02/palettegram/assets/108569153/22462506-53e7-4d34-add9-ca5febadd51e)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Yeah, the contributor tried to align but it couldn't. If you want you can try. 

Assigned to you

**Comment by Sanchitbajaj02** [comment]
Since, I didn't get update, I'm assigning the issue
