### ISSUE TITLE
Bug: Start Tour Button missing from Sidebar 

### ISSUE THREAD

**Issue by codercake** [Sanchitbajaj02/palettegram#358]
### What happened?

**Description**

The "Start Tour" button is not appearing in the sidebar on the landing page. This button is crucial for onboarding new users and familiarizing them with the platform's functionalities.

**Steps to Reproduce:**

1. Visit the DG landing page
2. Verify that the sidebar is present on the left-hand side of the screen
3. Check that the "Start Tour" button is missing from the sidebar

**Related Issues**
This issue seems to be particularly prevalent for users on mobile devices or small screens. Since the sidebar layout might not be optimized for smaller viewports, the button might be getting hidden or pushed off-screen.

### Add screenshots

![Screenshot (10)](https://github.com/Sanchitbajaj02/palettegram/assets/117517206/0bd7c7e1-96e2-4269-a6e2-de5dd0b108dd)

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @codercake, assigned this issue to you. You will be assigned only 1 point since it is very minor change
