### ISSUE TITLE
Feat ✨: Add Scroll-To-Top Button Matching to Website Design Theme

### ISSUE THREAD

**Issue by MastanSayyad** [Sanchitbajaj02/palettegram#363]
### What feature?

Hey @Sanchitbajaj02 

implementing a scroll-to-top button can enhance user experience by providing a convenient way for users to quickly return to the top of the page.

I would like to take on this task, Could you please assign this issue to me under GSSOC'24?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @MastanSayyad 
yeah we are missing this feature, thanks for pointing it out. Assigned to you
