### ISSUE TITLE
Bug: The number of stars on Git is not updated on the website

### ISSUE THREAD

**Issue by partha120804** [Sanchitbajaj02/palettegram#367]
### What happened?

I want to solve this issue

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/138643473/75b26f21-0b1b-48f3-a1b0-55cd4e57b590)

### What browsers are you seeing the problem on?

Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hey, @partha120804 
How are you planning to solve this issue?

**Comment by partha120804** [comment]
@Sanchitbajaj02 
I will use github api to fetch the current number of stars, everytime the page loads

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 
> I will use github api to fetch the current number of stars, everytime the page loads

If you have noticed, I have currently implemented that

**Comment by partha120804** [comment]
Ok
