### ISSUE TITLE
Bug: Got Error 412  when logging in with Google/GitHub

### ISSUE THREAD

**Issue by Anu-S-M** [Sanchitbajaj02/palettegram#368]
### What happened?

When attempting to log in using Google or GitHub authentication providers on the deployed website hosted on Vercel, users encounter 'Error 412: This provider is disabled.' This error prevents users from successfully logging in with their Google or GitHub accounts. The issue seems to be specific to these authentication methods and does not occur with other authentication providers. It's important to note that both Google and GitHub authentication providers are properly configured and enabled in the Appwrite console.
![Screenshot 2024-06-08 235332](https://github.com/Sanchitbajaj02/palettegram/assets/117372780/6310be8a-f973-4dce-8ac9-84cab1a1efe7)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
> I would like to work on this issue. Please assign this @Sanchitbajaj02

Authentication with google and github is implemented. Only the production isn't compatible with it so it was not working on it
