### ISSUE TITLE
Bug: No proper Icon display after entering password in login and register Page

### ISSUE THREAD

**Issue by Prithwi32** [Sanchitbajaj02/palettegram#370]
### What happened?

After writing password in placeholder of password in Register and login page,
 for a few seconds it displays both show and hide password icons..it should not happen only one icon should display

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/115262737/3b3c7cea-6573-44b7-be57-4a89ece29d38)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Prithwi32** [comment]
@Sanchitbajaj02 I want to work on this issue under gssoc'24

**Comment by Sanchitbajaj02** [comment]
Hi @Prithwi32 this is due to because the second is coming from the browser itself. Maybe you are using it on microsoft edge. Can you check on different browsers and let me know if it occurs again

**Comment by Prithwi32** [comment]
> Hi @Prithwi32 this is due to because the second is coming from the browser itself. Maybe you are using it on microsoft edge. Can you check on different browsers and let me know if it occurs again

Yes ....I will check and let u know

**Comment by Prithwi32** [comment]
> Hi @Prithwi32 this is due to because the second is coming from the browser itself. Maybe you are using it on microsoft edge. Can you check on different browsers and let me know if it occurs again

@Sanchitbajaj02  yes I have tested this In chrome and brave, only in edge it's displaying like this..

**Comment by Sanchitbajaj02** [comment]
I think we can close this issue then. What do you say??

**Comment by Prithwi32** [comment]
> I think we can close this issue then. What do you say??

okay..let we know if u could assign me with other issues

**Comment by Sanchitbajaj02** [comment]
> > I think we can close this issue then. What do you say??
> 
> okay..let we know if u could assign me with other issues

you can select any open issues
