### ISSUE TITLE
improve the footer 

### ISSUE THREAD

**Issue by jayanththalla** [Sanchitbajaj02/palettegram#372]
### What feature?

In the footer, the description I want to add and the social media icons  are missing.

 

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/121346142/4b9e8269-5e0e-41c3-8989-1157ad6ca2d3)
please assign me @pa
please label gssoc and the level

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @jayanththalla, the description is missing, and it is required. As for the icons, the code is already implemented since currently it doesn't have any social media accounts to link.
You can work on it
