### ISSUE TITLE
Bug: Submit button freezed 

### ISSUE THREAD

**Issue by dipanshu999** [Sanchitbajaj02/palettegram#373]
### What happened?

In the https://palettegram.vercel.app/feed page the post seems like it got frozen. It is not submitting the response given by the user.

### What browsers are you seeing the problem on?

Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @dipanshu999, this issue has already been raised under issue #364 
So, closing this issue since it is a delicacy.
