### ISSUE TITLE
Feat: Adding Google oauth 

### ISSUE THREAD

**Issue by mukilan2815** [Sanchitbajaj02/palettegram#375]
### What feature?

Assign this under GSSOC'24 level 3 . I can implement the Google auth functionality

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/71129858/5273adb4-82ba-4d51-8ba1-4f9870c6b5d6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @mukilan2815 if you have analyzed the code, the functionality is already built and their updations are already assigned in #284 
Closing this issue since it is a duplicate
