### ISSUE TITLE
Bug: Cursor Disappears Inside Tour Popup

### ISSUE THREAD

**Issue by rajdesai17** [Sanchitbajaj02/palettegram#376]
### What happened?

When opening the Tour popup on the platform, the cursor disappears entirely when we move it over the popup box. This makes it hard to interact with "next" button within the tour popup box.
The expected behavior would be for the cursor to remain visible within the popup, allowing users to click on buttons and navigate the tour content. The missing cursor creates a frustrating experience as it hinders the intended functionality of the tour.

### Add screenshots

![Screenshot 2024-06-13 113907](https://github.com/Sanchitbajaj02/palettegram/assets/118588662/13e0a4d6-fd6c-433b-836d-71d4ef8c7a2f)
![Screenshot 2024-06-13 113926](https://github.com/Sanchitbajaj02/palettegram/assets/118588662/20c8c29c-7fc3-4d1c-9153-55621b2cf48d)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @rajdesai17 I didn't even notice till now. Good catch. assigned to you

**Comment by Amitooo1** [comment]
Hey @Sanchitbajaj02 i recently worked on tour popup messages alignment issue and realised that this "animated cursor" is not that good feature to be implemented. This slows down the user speed to switch between pages or different content on same page. It would be better if we rollback to our old cursor.

**Comment by Sanchitbajaj02** [comment]
> Hey @Sanchitbajaj02 i recently worked on tour popup messages alignment issue and realised that this "animated cursor" is not that good feature to be implemented. This slows down the user speed to switch between pages or different content on same page. It would be better if we rollback to our old cursor.

I feel it is good, feels a little slow but gives a modern impression.

**Comment by Amitooo1** [comment]
> > Hey @Sanchitbajaj02 i recently worked on tour popup messages alignment issue and realised that this "animated cursor" is not that good feature to be implemented. This slows down the user speed to switch between pages or different content on same page. It would be better if we rollback to our old cursor.
> 
> I feel it is good, feels a little slow but gives a modern impression.

okay okay, i would love to work on this then : )

**Comment by Sanchitbajaj02** [comment]
> > > Hey @Sanchitbajaj02 i recently worked on tour popup messages alignment issue and realised that this "animated cursor" is not that good feature to be implemented. This slows down the user speed to switch between pages or different content on same page. It would be better if we rollback to our old cursor.
> > 
> > 
> > I feel it is good, feels a little slow but gives a modern impression.
> 
> okay okay, i would love to work on this then : )

Since, he didn't respond till last week, so assigned to you

**Comment by Sanchitbajaj02** [comment]
@Amitooo1 what is the status? if i don't get the status, I am assigning by EOD

**Comment by amanjaiswal7236** [comment]
Hey @Sanchitbajaj02 can I work on this issue under GSSOC' 24 ??

**Comment by Amitooo1** [comment]
Hey @Sanchitbajaj02 sorry I'm out of station you can assign to next person.

**Comment by Tomkndn** [comment]
If no one is working, kindly assign me.

**Comment by Sanchitbajaj02** [comment]
> If no one is working, kindly assign me.

assigned to you

**Comment by SuperSahitya** [comment]
I have created a PR to fix the issue of the animated cursor appearing under the Tour Popup by changing the z-index. I have also attached a screenshot of the fix in the PR for verification.

**Comment by Sanchitbajaj02** [comment]
> I have created a PR to fix the issue of the animated cursor appearing under the Tour Popup by changing the z-index. I have also attached a screenshot of the fix in the PR for verification.

PR has been reviewed and ready to merge. Thanks for contributing
