### ISSUE TITLE
Bug: Text input field for email in newsletter 

### ISSUE THREAD

**Issue by PranavKeshav24** [Sanchitbajaj02/palettegram#379]
### What happened?

The text input field designated for email addresses in the newsletter subscription form is currently using an <input> tag of type text instead of the appropriate type email. This issue impacts the user experience by not providing the necessary validation for email addresses, leading to potential input errors.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/127531721/b441ac0f-2472-4c83-be40-36cb99114218)

Please assign this issue to me. I am a contributor at GSSoC' 24. I would be very happy to work on it.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Brave, Other

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by yashd-dev** [comment]
Hi there, could you also include a [email regex pattern](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern) aswell?

**Comment by PranavKeshav24** [comment]
@yashd-dev Sure, I'll do that.

**Comment by SuperSahitya** [comment]
I have created a PR to fix this issue. Since the input type 'email' already has validations in place, I do not see the need to add another regex pattern for email unless we want to allow specific domains or provide custom warnings for incorrect email input.
