### ISSUE TITLE
Bug: Console logs not omitted in the build 

### ISSUE THREAD

**Issue by PranavKeshav24** [Sanchitbajaj02/palettegram#380]
### What happened?

The application contains console log statements that have not been removed in the production build. This issue can lead to performance degradation, unnecessary exposure of internal logic, and potential security risks. The logs in question are visible in the browser's console during runtime.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/127531721/290582fd-41b6-4dd7-b6b2-5af7a122b7c3)

Please assign this issue to me. I am a contributor at GSSoC' 24. I would be very happy to work on it.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Brave, Other

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by PranavKeshav24** [comment]
@yashd-dev Sure, I'll keep that in mind.

**Comment by yashd-dev** [comment]
Since this issue is minor, I have just assigned the gssoc label to grant you 1 point.

**Comment by SuperSahitya** [comment]
@Sanchitbajaj02 I have created a PR addressing this issue. I have commented out unnecessary logs while keeping the logs that report errors.
