### ISSUE TITLE
Feat: Like Post

### ISSUE THREAD

**Issue by Sid-80** [Sanchitbajaj02/palettegram#384]
### What feature?

Adding like post feature!

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/101277141/36a1dd79-db10-4f24-9a03-e63957b7863d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Like post feature has already been in progress and its issue is already opened, so closing this issue as it is a duplicate
