### ISSUE TITLE
Feat: Add Preloader

### ISSUE THREAD

**Issue by AsmitaMishra24** [Sanchitbajaj02/palettegram#386]
### What feature?

**Design and Appearance:**
1. A simple and visually appealing animation.
2. Should match the overall design language of the application.
3. Customizable options for color, size, and style to fit different themes.

**Functionality:**
1. Should display during the loading of heavy components or data fetching processes.
2. Must cover the main content area that is being loaded.
3. Option to show the preloader globally (entire screen) or locally (specific component).

**Performance:**
1. Lightweight and optimized to prevent additional load times.
2. Should not interfere with the loading process of the main content.

**Implementation:**
1. Should be implemented as a reusable component.
2. Easy to integrate with different parts of the application.
3. Must include appropriate documentation for usage and customization.

### Add screenshots

![maxresdefault](https://github.com/Sanchitbajaj02/palettegram/assets/146121869/07ca05a6-63a6-468b-a6d3-a27cdbf104a6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @AsmitaMishra24,
currently, if you notice there is a loader already implemented. How is yours going to be different than the existing one?
