### ISSUE TITLE
Bug: Cursor not visible on the cards opened by on clicking start tour button. 

### ISSUE THREAD

**Issue by amanjaiswal7236** [Sanchitbajaj02/palettegram#389]
### What happened?

When the cursor is not visible on cards that are opened by clicking the "Start Tour" button, it typically indicates an issue related to CSS styles or z-index conflicts within the web application. This problem can affect user interaction and overall user experience, as it prevents users from seeing the cursor and interacting with the elements effectively.

### Add screenshots

![Screenshot (828)](https://github.com/Sanchitbajaj02/palettegram/assets/124071449/7f335c57-3712-4279-b30c-3a96ddf148b7)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by amanjaiswal7236** [comment]
Can you assign it to me under GSSOC'24 ??

**Comment by Sanchitbajaj02** [comment]
Hi @amanjaiswal7236, if you notice, this issue is similar to #376, you can ask for assigning there. Closing this issue since it is a duplicate
