### ISSUE TITLE
Feat: Automated thank you email for newsletter subscription

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [Sanchitbajaj02/palettegram#391]
### What feature?

I would like to add a feature where an appreciation mail is sent to the user on newsletter subscription. This can be done either using emailjs or nodemailer. The mail would say something like "Welcome to Palettegram Newsletter. Thank you for subscribing to our newsletter. Stay tuned for more updates....".
And also add an alert with a message "Subscribed to Newsletter" when the subscribe button is clicked. This would improve the overall user experience.

@Sanchitbajaj02, please assign this issue to me under GSSoC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Ayesha-Siddiqua88 
we can implement that. Currently, there is a system of resend api which might help you in sending the email.
