### ISSUE TITLE
Style: cursor pointer on cross icon

### ISSUE THREAD

**Issue by 2004shivanshi** [Sanchitbajaj02/palettegram#394]
### What's the suggested design idea?

After starting the tour, a modal opened, but when I wanted to close or click next , the cursor pointer did not appear.

![Screenshot 2024-07-04 024228](https://github.com/Sanchitbajaj02/palettegram/assets/140749222/e79ad249-0bd7-4316-9c8b-d9fee5f63943)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @2004shivanshi 
The issue is already created and assigned to somebody so closing this as it seems duplicate
