### ISSUE TITLE
Feat:  Smooth Scroll Using Lenis

### ISSUE THREAD

**Issue by TenzDelek** [Sanchitbajaj02/palettegram#397]
### What feature?

smooth scroll for better UX experience

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @TenzDelek 
What is Lenis? and does the smooth scrolling be done using the existing tailwind CSS?

**Comment by TenzDelek** [comment]
> Hi @TenzDelek 
> 
> What is Lenis? and does the smooth scrolling be done using the existing tailwind CSS?

https://github.com/darkroomengineering/lenis here's a link repo of Lenis. It kind of a lightweight library used for smooth scrolling. 
I believe for smooth scroll with this might be a better option rather than tailwind. Here's a demo: https://tenzindelekdesign.vercel.app

**Comment by TenzDelek** [comment]
> > Hi @TenzDelek 
> > 
> > What is Lenis? and does the smooth scrolling be done using the existing tailwind CSS?
> 
> https://github.com/darkroomengineering/lenis here's a link repo of Lenis. It kind of a lightweight library used for smooth scrolling. 
> I believe for smooth scroll with this might be a better option rather than tailwind. Here's a demo: https://tenzindelekdesign.vercel.app

Cc @Sanchitbajaj02

**Comment by Sanchitbajaj02** [comment]
> > Hi @TenzDelek
> > What is Lenis? and does the smooth scrolling be done using the existing tailwind CSS?
> 
> https://github.com/darkroomengineering/lenis here's a link repo of Lenis. It kind of a lightweight library used for smooth scrolling. I believe for smooth scroll with this might be a better option rather than tailwind. Here's a demo: https://tenzindelekdesign.vercel.app

Looks amazing, you can incorporate that, assigned to you.
Just for my knowledge and confirmation, didn't scroll-behaviour property of CSS do the same work?

**Comment by TenzDelek** [comment]
> > > Hi @TenzDelek
> 
> > > What is Lenis? and does the smooth scrolling be done using the existing tailwind CSS?
> 
> > 
> 
> > https://github.com/darkroomengineering/lenis here's a link repo of Lenis. It kind of a lightweight library used for smooth scrolling. I believe for smooth scroll with this might be a better option rather than tailwind. Here's a demo: https://tenzindelekdesign.vercel.app
> 
> 
> 
> Looks amazing, you can incorporate that, assigned to you.
> 
> Just for my knowledge and confirmation, didn't scroll-behaviour property of CSS do the same work?

It kinda same but the damping is much better
