### ISSUE TITLE
Feat: Adding Chatbot to website

### ISSUE THREAD

**Issue by Ojas-Arora** [Sanchitbajaj02/palettegram#399]
### What feature?

@Sanchitbajaj02 I  want to add chatbot to website. kindly assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Ojas-Arora 
Can you describe your issue. What kind of chat bot it will be, what problem it resolves, how you are going to implement it? please give me an overview

**Comment by Ojas-Arora** [comment]
@Sanchitbajaj02  I am making a chatbot using Tidio for Palettegram, a social media application for professionals like graphic designers, UI/UX designers, and developers. This chatbot will enhance user experience by assisting with finding color palettes, design ideas, and UX approaches, and providing a streamlined workflow for contributing to the community.

**Comment by Sanchitbajaj02** [comment]
So Tidio gives the AI Chatbot that I can configure using my keys. Then if someone asks the questions, it just works like chat gpt or other AI models. Right?

**Comment by Ojas-Arora** [comment]
@Sanchitbajaj02 Yes but u will need to add some details about your website

**Comment by Sanchitbajaj02** [comment]
Seems nice, you can work on that. With which event you are associated with?

**Comment by Ojas-Arora** [comment]
@Sanchitbajaj02  Sir Gssoc 24
