### ISSUE TITLE
Feat: By-pass email verification on development environment

### ISSUE THREAD

**Issue by vinayak-vohra** [Sanchitbajaj02/palettegram#404]
### What feature?

Currently email verification is required even in development environment. This creates hinderance when developing & testing features which require multiple accounts. (such as like, comments etc.)

I propose we bypass the email verification in development environment and use it only in the production environment.
This will allow the developers to use any email on their local environment, improving developer experience and efficiency .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @vinayak-vohra 
Can you explain me your proposal on how you are going to implement it?

**Comment by vinayak-vohra** [comment]
@Sanchitbajaj02 sure. 
- Using the environment variable `NODE_ENV` we can check the mode i.e., 'development' or 'production'.
- Then adding simple check before sending the verification email. Only send if env is production.
- Finally, in `middleware.ts` we have checks to redirect to homepage if user is not verified. We can add another condition to check for the environment and only redirect when in production mode.

When starting the server in dev mode using `yarn dev`, no verification email is sent, and the middleware logic allows access to site without the need of verification.

When starting the server in production mode by `yarn build` and `yarn start`, the site will behave as it currently is.

**Comment by vinayak-vohra** [comment]
@Sanchitbajaj02 I just found a better approach. When creating user account after register, set the `isVerified` attribute as true when in development environment. We won't need to change anything in the middleware.
