### ISSUE TITLE
Bug: want to make register and signup page load in new tab

### ISSUE THREAD

**Issue by Shreyaa173** [Sanchitbajaj02/palettegram#407]
### What happened?

register and signup page is opening in the same tab

### Add screenshots

![image](https://github.com/user-attachments/assets/b0d80581-a6e5-4c6f-a0ca-0135baf45596)

### What browsers are you seeing the problem on?

Microsoft Edge

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Shreyaa173 Signup page is register page. Some people like to call it register others name is signup.
