### ISSUE TITLE
Add Cursor Trail Effect Matched to Website Design Theme

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Sanchitbajaj02/palettegram#416]
### What feature?

Hey @Sanchitbajaj02 

We aim to enhance the user experience on our website by adding a cursor trail effect that aligns with our current website design theme. The cursor trail effect should be visually appealing and not interfere with the website's usability.

### Add screenshots

like this

https://github.com/user-attachments/assets/ca61be1d-83a9-48d9-9d0c-b0a192e09a54

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @RadhikaMalpani1702 
does this feature be easily implement with the existing cursor event?

**Comment by RadhikaMalpani1702** [comment]
@Sanchitbajaj02 The current one is react in-build cursor but I would like to add a trail effect to it. I can try to make them co-exist

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 The current one is react in-build cursor but I would like to add a trail effect to it. I can try to make them co-exist

Sure assigned to you

**Comment by SrisharanVS** [comment]
Hey @Sanchitbajaj02, I would like to work on this issue, can you assign this to me?

**Comment by Sanchitbajaj02** [comment]
> Hey @Sanchitbajaj02, I would like to work on this issue, can you assign this to me?

Sure, assigned to you
