### ISSUE TITLE
Feat: Adding a website scroll indicator on top

### ISSUE THREAD

**Issue by Sourabh782** [Sanchitbajaj02/palettegram#417]
### What feature?

Addition of a dynamic website scroll indicator on top.

### Add screenshots

![Screenshot 2024-08-04 162553](https://github.com/user-attachments/assets/0004fe74-f234-43e4-b94c-bd4dca95e8f0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hi @Sourabh782 
Yeah we can add that. This functionality is already build in some other component so, you can reuse that css
