### ISSUE TITLE
Bug: Localstorage undefined error

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#47]
### What happened?

While developing for production build, the application is giving the error saying that the localstorage is undefined. If anyone knows the solution, they can offer.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/723b806b-aef7-4245-8de3-75df1811e868)

### What browsers are you seeing the problem on?

Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

**Comment by Kaybangz** [comment]
Hello Sanchit. I can see there's no assignee yet, can I work on this issue?

**Comment by Sanchitbajaj02** [comment]
@Kaybangz yeah sure, just try to remove the dependency with localstorage and make it a way to store it in cookies

**Comment by Sanchitbajaj02** [comment]
For landing page, you can wait, as I am planning to improve, you can make it responsive, just comment under that issue and I will assign it to you

**Comment by Kaybangz** [comment]
Alright

**Comment by Sanchitbajaj02** [comment]
@Kaybangz can you tell me the status of this issue?

**Comment by Kaybangz** [comment]
> @Kaybangz can you tell me the status of this issue?

I am almost done, I'll make a PR before the end of tomorrow.
Again, I apologise for the delay 🙏

**Comment by Sanchitbajaj02** [comment]
> > @Kaybangz can you tell me the status of this issue?
> 
> I am almost done, I'll make a PR before the end of tomorrow.
> Again, I apologise for the delay 🙏

No problem, take your time
