### ISSUE TITLE
Bug:  password error not showing 

### ISSUE THREAD

**Issue by Atharvashuks** [Sanchitbajaj02/palettegram#51]
### What happened?

the warning is not shown on the page when the password is less than 8 characters and it's not getting logged in.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/71465575/e745f77a-f6eb-474b-8bc8-edcc9bc2b295)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Hey @Atharvashuks thanks for raising the issue. I have added the changes. You can test them out and if you feel that the issue that you created is not implemented, let me know

**Comment by printf-ana** [comment]
Hello, I'm participating of hacktoberfest and I would love to resolve this bug, can you please assigned me for this issue?

**Comment by Atharvashuks** [comment]
Ok...

PS: aap ye muje WhatsApp pe bhi to bata sakte ho🤭🤭

**Comment by Sanchitbajaj02** [comment]
> Hello, I'm participating of hacktoberfest and I would love to resolve this bug, can you please assigned me for this issue?

The error is resolved partially, you can work on the notification toastify. I've created a toastify js file, you can implement toastifies where it is required

**Comment by Sanchitbajaj02** [comment]
Issue Resolved
