### ISSUE TITLE
Style: Responsive Web Design

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#55]
### What's the suggested design idea?

Currently the website is working great on desktop screen sizes but the moment screen size reduces under 1000px, it starts breaking. We have to find a solution to fix this behavior.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Kaybangz** [comment]
I would like to be assigned this issue

**Comment by Sanchitbajaj02** [comment]
The issue assigned to you

**Comment by Sanchitbajaj02** [comment]
> @Kaybangz Any update? Can I hijack this issue?

No update as of now. Although someone working on fixing the navbar at issue #65. You can wait for that first

**Comment by ashishk1331** [comment]
Okay.

**Comment by Kaybangz** [comment]
I apologize for the delay. Yes I am still working on the landing page, and I'll be making a PR soon

**Comment by Sanchitbajaj02** [comment]
@Kaybangz and @ashishk1331 if possible, both of you can discuss here and divide the pages if you want to.
Or else @ashishk1331 has to work on a different issue

**Comment by ashishk1331** [comment]
Let @Kaybangz cook.
