### ISSUE TITLE
Feat: A toggle button for dark mode

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#60]
### What feature?

Currently the web application has the capability to change the color of elements like background, text, buttons, etc but there is no toggle button which a user can use.
To change the theme of the website, user has to change the theme of their device.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by irfanfaraaz** [comment]
@Sanchitbajaj02 Can i work on this?

**Comment by Sanchitbajaj02** [comment]
@irfanfaraaz yeah sure, assigned to you.

**Comment by irfanfaraaz** [comment]
@Sanchitbajaj02 I implemented a toggle button. It's changing the theme in local storage, but it's not changing the theme of the app. Is there anything that I am missing?

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 I implemented a toggle button. It's changing the theme in local storage, but it's not changing the theme of the app. Is there anything that I am missing?

How are you changing the state in the component itself. You created the system to change the state in localstorage, but are you parsing it in the application?

**Comment by irfanfaraaz** [comment]
I guess that there's a conflict between the global styles and the styles applied by the theme provider.

When I commented out the below part from 'globals.css', it worked.

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(to bottom, transparent, rgb(var(--background-end-rgb)))
    rgb(var(--background-start-rgb));
}

**Comment by Sanchitbajaj02** [comment]
Can you confirm whether this css is applying anywhere or not? If not, then comment/remove it

**Comment by irfanfaraaz** [comment]
It is applying the background color

**Comment by Sanchitbajaj02** [comment]
![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/6cd23c4f-acac-4369-8e7f-a7d216cc267b)

Can you do something so that the background dependency will be removed from this?

**Comment by Sanchitbajaj02** [comment]
Just do one thing, in dark mode, can you use the colors what were used previously as that will be our brand colors

**Comment by irfanfaraaz** [comment]
Can I refer your figma design?

**Comment by Sanchitbajaj02** [comment]
I don't have a proper figma design, but you can refer the color shades that I am using in this project.

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/b4af6439-e5d8-4cfa-ac1e-ea6cf568bc65)

**Comment by irfanfaraaz** [comment]
I experimented with various approaches to implement the background change through globals.css. While text and icon colors are behaving as anticipated, I'm encountering an issue with the background. The background of the dark theme seems to be overriding the light theme. Unfortunately, despite my efforts, I'm currently unable to debug this issue.

**Comment by Sanchitbajaj02** [comment]
You can make a pr of your work up until now. Then I can analyse where we can enhance that feature
