### ISSUE TITLE
Docs: grammar issues

### ISSUE THREAD

**Issue by caycun** [Sanchitbajaj02/palettegram#67]
### What you want to add in the documentation?

I found some grammatical errors in the readme. Can you assign this to me?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Sure, you can work on the grammar issues

**Comment by jennifershinshin** [comment]
Hi! @Sanchitbajaj02 @caycun The Discord link in the readme is expired. Can you update it please?

**Comment by Sanchitbajaj02** [comment]
Sure I will update tomorrow
