### ISSUE TITLE
Feat: Update the environment variables example for nextjs

### ISSUE THREAD

**Issue by Shrest4647** [Sanchitbajaj02/palettegram#69]
### What feature?

The documentation of environment variables provided in .env.example is outdated and some variable names have been renamed in actual code. This issue is to update and set the correct environment variables for Appwrite and Nextjs.

### Add screenshots

- In .env.example
<img width="149" alt="image" src="https://github.com/Sanchitbajaj02/palettegram/assets/35072109/77eddcb3-9ae9-4857-b4b0-c095dd89e6cd">

- In the codebase
<img width="254" alt="image" src="https://github.com/Sanchitbajaj02/palettegram/assets/35072109/b32fc892-f512-4c2e-80a2-3941b5cc649b">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Assigned this issue to you
