### ISSUE TITLE
Bug: Failed to load resource: the server responded with a status of 401 ()

### ISSUE THREAD

**Issue by sid86-dev** [Sanchitbajaj02/palettegram#74]
### What happened?

After the form submission on the 'register' page, the redirection to the next screen, `/feed`, is unsuccessful. Although the account creation process is successful, it fails to load the required data, resulting in the following error.

```
Invalid 'url' param: URL host must be one of: localhost, cloud.appwrite.io, *vercel. app,
192.168.1.38
```

### Add screenshots

![Screenshot 2023-10-16 at 6 42 41 PM](https://github.com/Sanchitbajaj02/palettegram/assets/74738350/1da6107e-e705-46f2-a74e-078529892117)

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
@sid86-dev my intuition says there is some issue related to environment variables, can you do the analysis for this issue?

**Comment by sid86-dev** [comment]
What I believe to be a potential solution is updating the allowed host domain within the Appwrite console. Try adding the full domain of the app's deployed `URL` (vercel).

**Comment by sid86-dev** [comment]
**CORS** error from appwrite, please allow host `http://localhost:3000`

**Comment by Sanchitbajaj02** [comment]
Localhost is allowed by default from appwrite.
