### ISSUE TITLE
Feat: Profile link button for authenticated user

### ISSUE THREAD

**Issue by sid86-dev** [Sanchitbajaj02/palettegram#76]
### What feature?

When a user has already been `authenticated` and arrives at the **landing page**, provide them with an intuitive button option in the navbar, allowing for a smooth and immediate redirection to either the `feed` or `profile` page.

### Add screenshots

<img width="491" alt="Screenshot 2023-10-16 at 7 14 22 PM" src="https://github.com/Sanchitbajaj02/palettegram/assets/74738350/eecedc33-8f3a-4643-8499-49a434dde326">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
@sid86-dev this is implemented. When a user is authenticated, the start your journey cta button of the hero section will change to check your feed.

**Comment by sid86-dev** [comment]
In the latest deployment preview, it appears that the `Start your journey` button remains static. However, if the upcoming commit addresses this issue, that would be an ideal solution.

**Comment by Sanchitbajaj02** [comment]
Actually, I have already implemented this feature. If it is not showing after the login. You can take up this issue to fix this
