### ISSUE TITLE
Docs: Update Discord Invite Link

### ISSUE THREAD

**Issue by jennifershinshin** [Sanchitbajaj02/palettegram#78]
### What you want to add in the documentation?

The Discord invite link in the Readme is expired. It needs to be updated.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
It is already updated

**Comment by Sanchitbajaj02** [comment]
https://discord.gg/s9v8WHUgfV

try this

**Comment by jennifershinshin** [comment]
Ok I got it. Interesting, it didn't work on Google Chrome but it did work on Brave.
Thank you!
