### ISSUE TITLE
Feat: A contribution page in the application

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#82]
### What feature?

I've seen many web apps having a 'How to configure page' or 'Contribution Docs' page into their website which contains some points and images for the new contributors so that they can contribute. So, I think this project also needs one.

### Add screenshots

References: 
- https://www.git-in.to/guides/local-git-setup
- https://projectshut.vercel.app/docs/

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by ShatilKhan** [comment]
@Sanchitbajaj02 please assign me

**Comment by Sanchitbajaj02** [comment]
Sure I will assign you but keep in mind that pr before 1 jan 2024 can't be considered

**Comment by Sanchitbajaj02** [comment]
@ShatilKhan since I didn't get any response so unassigning the issue

**Comment by mukundsolanki** [comment]
@Sanchitbajaj02 Can you assign me this issue, I am a contributor from IWOC24 and wanted to work onto this.

**Comment by Sanchitbajaj02** [comment]
Sure, assigned to you

**Comment by IrfanshaikH-7** [comment]
I wonder why no one is taking on this issue

**Comment by kamalsritha** [comment]
@Sanchitbajaj02 can you please assign me this issue under SWOC S4

**Comment by Sanchitbajaj02** [comment]
@kamalsritha assigned to you

**Comment by Manishak798** [comment]
@kamalsritha have you started working on this issue?

**Comment by kamalsritha** [comment]
@Manishak798 Yes i did

**Comment by Sanchitbajaj02** [comment]
@kamalsritha what is the status? if you don't inform within 24 hrs, I am unasigning you

**Comment by Girishbari** [comment]
assign me

**Comment by Sanchitbajaj02** [comment]
@Girishbari assign to you
