### ISSUE TITLE
Bug: No loading animation or effect or skeleton load

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#84]
### What happened?

When user navigates through different pages or perform some action, there is no way to detect whether the action initiated by user is started or not.
The solution of this problem is to add a loading animation/text to get the users to know that their action has been initiated.

### What browsers are you seeing the problem on?

Microsoft Edge, Brave

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by Sanchitbajaj02** [comment]
Loading Animation has been added on selective screen but needs improvement

**Comment by IrfanshaikH-7** [comment]
Hello ! can you help me in project setup! i think I'm missing something ..
i started the application but i can't register

**Comment by Sanchitbajaj02** [comment]
> Hello ! can you help me in project setup! i think I'm missing something .. i started the application but i can't register

This issue is related to the loading animation but. If you want to discuss, please message in the Palettegram discord channel. Thanks

**Comment by IrfanshaikH-7** [comment]
hello! I'd like to work on this issue. could you please assign me this issue,
and I'd like to know. where is this issue is happening.
as for me I encountered this issue in register and login button.

**Comment by Sanchitbajaj02** [comment]
> I'd like to know. where is this issue is happening.

This bug will occur when you visit on to /feed page. The feed posts come after some interval. So I was thinking, we can add a loading animation for users.

> as for me I encountered this issue in register and login button.

can you explain more about the issue

**Comment by IrfanshaikH-7** [comment]
there isn't a loading state for both the server action and i guess it's the same for every actions and as for the feed page we can use Next js Loading page to preview the page with a similar skeleton with some tailwind animate classes

**Comment by Sanchitbajaj02** [comment]
Yeah we can do that. Currently I am not looking for skeleton but you can if you want to. It looks great😊

**Comment by IrfanshaikH-7** [comment]
Sure ! i just switch my network to 3G I notice there is a loader but its sticked to the top we can use it too - I'll try skeleton . if it looks great will go for that

**Comment by Sanchitbajaj02** [comment]
> Sure ! i just switch my network to 3G I notice there is a loader but its sticked to the top we can use it too - I'll try skeleton . if it looks great will go for that

Yeah, that I implemented so that users who came to contribute can see the loading
