### ISSUE TITLE
Feat: Username display feature

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#90]
### What feature?

Currently the userId is exposed for a user when we see a profile. To fix that, a username should be there as it will be easy for the users instead of userId.

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/c7055ce2-7d42-487b-aee5-e5212d1c541c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

**Comment by Vidip-Ghosh** [comment]
I would like to work on this. Can you please assign?

**Comment by Sanchitbajaj02** [comment]
sure but the Pull Requests before 1 Jan 2024 are not considered, so keep in mind about it. 

Anyways assigned.

**Comment by krishnagitcontri** [comment]
@Sanchitbajaj02  can you please assign this to me i am confident that i can help you with this !!

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 can you please assign this to me i am confident that i can help you with this !!

Hi @krishnagitcontri I already assigned him this issue yesterday. If I didn't get his response, I will assign you the issue. Till then, you can explore more issues or create a new one

**Comment by krishnagitcontri** [comment]
can i do my PR in advance if he doesn't respond in case?

**Comment by Sanchitbajaj02** [comment]
> can i do my PR in advance if he doesn't respond in case?

You can but PR before 1 jan aren't considered in SWOC

**Comment by Vidip-Ghosh** [comment]
> can i do my PR in advance if he doesn't respond in case?

I will create my PR on 1st January. 
Since contributions start from 1st January

**Comment by Sanchitbajaj02** [comment]
> > can i do my PR in advance if he doesn't respond in case?
> 
> I will create my PR on 1st January. Since contributions start from 1st January

Sure but remember that preference will be given to @Vidip-Ghosh as he asked first to work on it

**Comment by Vidip-Ghosh** [comment]
<img width="802" alt="Screenshot 2023-12-30 at 23 10 48" src="https://github.com/Sanchitbajaj02/palettegram/assets/91741581/121f5590-fc7c-4a0f-a823-7b4698e67361">
After I clicked on post button, the post doesn't get displayed. I think is it because db is not able to fetch.

**Comment by Vidip-Ghosh** [comment]
> <img alt="Screenshot 2023-12-30 at 23 10 48" width="802" src="https://private-user-images.githubusercontent.com/91741581/293473196-121f5590-fc7c-4a0f-a823-7b4698e67361.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwMDk5MjksIm5iZiI6MTcwNDAwOTYyOSwicGF0aCI6Ii85MTc0MTU4MS8yOTM0NzMxOTYtMTIxZjU1OTAtZmM3Yy00YTBmLWE4MjMtN2I0Njk4ZTY3MzYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMxVDA4MDAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MmI5NTRkNDg5NTQ5ZDUxYTRhMzMzMzJhMTg3YzU3OTY4Y2VjNjM5YzA1M2ZhYmU0MTBjMTRjNWI0MGEyZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0YoDKxNTghsJGXWOzvqZS7THCcVmCLeC-veYrO44Ni4"> After I clicked on post button, the post doesn't get displayed. I think is it because db is not able to fetch.

@Sanchitbajaj02 please tell what to do?

**Comment by Sanchitbajaj02** [comment]
> After I clicked on post button, the post doesn't get displayed. I think is it because db is not able to fetch.

Did you try to refresh the page? Because the moment you added the post, it should be displayed in the feed and if by any chance it didn't get displayed, a simple page refresh would make it visible in the feed.

**Comment by Vidip-Ghosh** [comment]
> > After I clicked on post button, the post doesn't get displayed. I think is it because db is not able to fetch.
> 
> Did you try to refresh the page? Because the moment you added the post, it should be displayed in the feed and if by any chance it didn't get displayed, a simple page refresh would make it visible in the feed.

Its still not showing.

**Comment by Sanchitbajaj02** [comment]
Can you properly list down the steps to achieve that?

**Comment by Vidip-Ghosh** [comment]
@Sanchitbajaj02 could you pls check on your end if its working or not?

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 could you pls check on your end if its working or not?

Can you check now. I have done some changes
