### ISSUE TITLE
Feat: User profile page

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#91]
### What feature?

Currently user profile page just show the user's email and a message `No posts yet`.

if the user has posted more than 1 post, the page should show that instead.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by iSubhamMani** [comment]
Hi! I would like to work on this issue. Can you assign it to me ?

**Comment by Sanchitbajaj02** [comment]
> Hi! I would like to work on this issue. Can you assign it to me ?

Sure you can work on this issue. Assigned
