### ISSUE TITLE
Bug: bookmark does not working properly

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#93]
### What happened?

The bookmark feature is working fine but the problem is that you can not bookmark others' post. You can only save/remove bookmark of your own post. The problem might be related to id comparison or state issue

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge, Brave

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I want to work on this issue

**Comment by utkarsh4321** [comment]
@Sanchitbajaj02 is this issue still exist i m uanble to see
![Uploading image.png…]()

**Comment by Sanchitbajaj02** [comment]
Last time I checked, I wouldn't be able to bookmark the posts which are not mine. 

If you are not facing any issues then let me know. I will close this issue.

**Comment by utkarsh4321** [comment]
Hi @Sanchitbajaj02  I not created any post there. These one are not mine post in SS. And I m able to bookmark them. I m not facing above mentioned issue. Please check on your end as well. Thankyou

**Comment by Sanchitbajaj02** [comment]
> Hi @Sanchitbajaj02 I not created any post there. These one are not mine post in SS. And I m able to bookmark them. I m not facing above mentioned issue. Please check on your end as well. Thankyou

Sure, thanks for informing. If I couldn't able to reproduce it as well using multiple accounts of mine. I will close the issue. 

In the meantime you can checkout more issues or create one if you faced any😊

**Comment by utkarsh4321** [comment]
@Sanchitbajaj02 if you are able to reproduce that issue. Please let me know so I will try to fix it.

**Comment by Sanchitbajaj02** [comment]
> @Sanchitbajaj02 if you are able to reproduce that issue. Please let me know so I will try to fix it.

I got the error again.

### Steps to reproduce:

- I created a second account.
- Use that account to bookmark the post which isn't mine.
- got the below issue.
![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/e31c9abb-0213-4dea-892d-1654ea09a266)

**Comment by utkarsh4321** [comment]
@Sanchitbajaj02 I will check it. To reproduce if not able to reproduce I will connect with you on this.

**Comment by utkarsh4321** [comment]
@Sanchitbajaj02 I tried it here I'm not able to apply a bookmark on multiple posts. This problem I'm facing. But i'm not getting any errors as of now. As you showed above.

**Comment by utkarsh4321** [comment]
@Sanchitbajaj02  Added Pr for this please check. If anything else is required please let me know. Thankyou
