### ISSUE TITLE
Feat: Color picker generator (Work with Admin)

### ISSUE THREAD

**Issue by Sanchitbajaj02** [Sanchitbajaj02/palettegram#98]
### What feature?

Currently the feature to choose colors is not supported well. Although the configuration is present in the code but it is not setup as expected.
To get the reference of what I am expecting, checkout [this](https://colorhunt.co/).

### Add screenshots

![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/69fb5cd0-7882-4098-9eab-3a31b2f013a3)

This card will be shown with the option to choose colors when click on the icon:
![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/927f171e-ad28-4659-ae57-50e196ffe6d7)

### Currently, it is looking like this:
![image](https://github.com/Sanchitbajaj02/palettegram/assets/55249639/2d52d4ff-eca0-4352-98e9-650ede7f9d13)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I want to work on this issue

**Comment by sohail300** [comment]
Hey, can u assign me this issue?

**Comment by Sanchitbajaj02** [comment]
Sure, I can. But first can you give me a brief about your approach? Like what you are going to use to achieve the result

**Comment by sohail300** [comment]
Yes, I am configuring all the things. Will follow you up after configured all the things.

**Comment by praptisharma28** [comment]
Assign me @Sanchitbajaj02 under iwoc2024, would love to do!

**Comment by Sanchitbajaj02** [comment]
@praptisharma28 assigned this to you. But remember to contact me on each step

**Comment by praptisharma28** [comment]
@Sanchitbajaj02 , the problem I can see is that the color picker is matching the color I write in 2nd with 3rd and 4th. If I am not wrong, this is the exact issue you want me to solve right?

**Comment by Sanchitbajaj02** [comment]
@praptisharma28 I want you to create this feature from scratch. The existing/current feature is not working at all. Also please checkout the reference as well

**Comment by praptisharma28** [comment]
Sure @Sanchitbajaj02

**Comment by Sanchitbajaj02** [comment]
> @praptisharma28 I also want to work on it. If you want we together work on it. @Sanchitbajaj02 If I will also work you consider my contribution on it ?

I first have to discuss this case with admins since you both are registered in different events so tracking might work differently.

**Comment by Sanchitbajaj02** [comment]
@praptisharma28 and @utkarsh4321 

Is there any progress or are you guys stuck? I think you both can work on it since you both are in different events

**Comment by utkarsh4321** [comment]
Hi @Sanchitbajaj02 not started yet. Due to your comments. Let's discuss on this. What you actually want then I can plan things accordingly. So let's connect whenever you free.

**Comment by Sanchitbajaj02** [comment]
@utkarsh4321 No worries, you both can now work on it. Assigning to both.

**Comment by thevirengarg** [comment]
@utkarsh4321 @praptisharma28 You guys have 24 hours to raise a PR else i will unassign you this issue.

**Comment by utkarsh4321** [comment]
@thevirengarg  i have completed my findings on this. Will connect with @Sanchitbajaj02  and discuss the approach. And then I will try to create PR on this. Thankyou

**Comment by Sanchitbajaj02** [comment]
@thevirengarg I am taking this issue myself, so don't worry if @utkarsh4321 takes time and since @praptisharma28 didn't respond, I am unassigning him

**Comment by Girishbari** [comment]
if I am not mistaken this is what you want to achieve @Sanchitbajaj02 right..?
![image](https://github.com/Sanchitbajaj02/palettegram/assets/38005544/f2127aa1-141f-4d27-bd71-1d1606c0cf68)

also what's the update on this

**Comment by Sanchitbajaj02** [comment]
@utkarsh4321 yeah the design is good and I want to achieve this.

**Comment by utkarsh4321** [comment]
@Sanchitbajaj02 created PR please review it and let me know if anything else is needed.
